/* Ver.0.43 Auto Improvement Lab. Manifests and isolated paired AI A/B; never deploys. */
(function(){'use strict';
const KEY='tactics7_auto_improvement_v043',clone=v=>JSON.parse(JSON.stringify(v)),now=()=>new Date().toISOString(),R=window.RULES;
function gate(report){let n=report?.core?.validMatches||0,t=report?.core?.testers||0,counts=Object.values(report?.core?.testerMatches||{}),share=n?Math.max(0,...counts)/n:1,balanced=report?.core?.testerBalanced?.winRatePct,weighted=report?.core?.matchWeightedWinRatePct,diff=Number.isFinite(balanced)&&Number.isFinite(weighted)?Math.abs(balanced-weighted):null,testerSpecific=share>.6&&n>=5;let level=n<20?'OBSERVE':n<50?'PROPOSE':'AUTO_AB';if(t<5||testerSpecific)level=level==='OBSERVE'?'OBSERVE':'PROPOSE';return{level,humanMatches:n,testers:t,largestTesterSharePct:+(share*100).toFixed(1),matchVsTesterDiffPct:diff,testerSpecific,allowed:{observe:true,propose:level!=='OBSERVE',autoAB:level==='AUTO_AB'&&!testerSpecific},reason:n<20?'20試合未満：観測のみ':testerSpecific?'Tester-specific possibility：自動A/B不可':t<5?'Tester数5未満：自動A/B不可':level==='PROPOSE'?'20〜49試合：提案のみ':'50試合以上かつTester偏りゲート通過'}}
function classify(bucket,c){if(bucket==='fun')return'FUN';if(bucket==='ux')return /drag|cancel|操作/i.test((c.title||'')+(c.evidence||''))?'INPUT_USABILITY':'UX_CLARITY';if(bucket==='ai')return'AI_BEHAVIOR';if(bucket==='balance')return /class|クラス|Kingdom|Forest|Arcane|Nether|Mechanica|Abyss|王国|森域|魔導|冥界|機巧|深淵/.test(c.title||'')?'CLASS_BALANCE':'CARD_BALANCE';return'UNKNOWN'}
function sources(report){let out=[];for(const [bucket,rows] of Object.entries(report?.candidates||{}))for(const c of rows)out.push({sourceId:`${bucket}-${out.length+1}`,bucket,type:classify(bucket,c),title:c.title,evidence:c.evidence,confidence:c.confidence,priority:c.priority,humanSample:report.core.validMatches,aiSample:(c.evidence||'').includes('AI')?'Ver.0.37 Phase 1 aggregate':'not linked',effectSize:c.evidence,version:report.filters||{},related:[]});return out}
function manifest(x){return{candidateId:x.candidateId,baseVersion:'0.41',sourceCandidate:x.sourceCandidate||'DRY_RUN_AI_BASELINE',type:x.type||'CARD_BALANCE',hypothesis:x.hypothesis,changedFiles:['candidate_overrides.js (runtime research override only)'],changedValues:x.changedValues,expectedEffect:x.expectedEffect,possibleSideEffects:x.possibleSideEffects||[],humanEvidence:x.humanEvidence||'Human n=1：修正根拠に使用しない',aiEvidence:x.aiEvidence||'Ver.0.37 王国 AI勝率69.48%',status:'DRAFT',dryRun:!!x.dryRun,createdAt:now(),oneVariable:x.changedValues?.length===1,requiresHumanValidation:true,productionApplied:false}}
function dryRunManifests(){return[
 manifest({candidateId:'dry-kingdom-10-cost-plus-1',dryRun:true,hypothesis:'使用可能時期を1 Player Turn遅らせ、王国の終盤圧力だけを弱める',changedValues:[{path:'cards.p1_Kingdom_10.cost',from:8,to:9}],expectedEffect:'王国の終盤勝率低下',possibleSideEffects:['手札で腐る率上昇','決着遅延']}),
 manifest({candidateId:'dry-kingdom-10-hp-minus-1',dryRun:true,hypothesis:'生存性だけを下げ、フィニッシャー再攻撃率を抑える',changedValues:[{path:'classes.p1_Kingdom_10_unit.hp',from:6,to:5}],expectedEffect:'除去可能性上昇',possibleSideEffects:['防衛価値低下','魔導との相性変化']}),
 manifest({candidateId:'dry-kingdom-10-melee-minus-1',dryRun:true,hypothesis:'継続火力だけを下げ、登場時の盤面効果は残す',changedValues:[{path:'classes.p1_Kingdom_10_unit.melee',from:2,to:1}],expectedEffect:'COMMANDER継続圧力低下',possibleSideEffects:['8 COSTとして弱すぎる可能性']})]}
function snapshot(m){return m.changedValues.map(v=>{let [root,id,field]=v.path.split('.'),obj=root==='cards'?R.cards[id]:R.classes[id];return{obj,field,value:obj[field]}})}
function apply(m){let snap=snapshot(m);for(let i=0;i<m.changedValues.length;i++)snap[i].obj[snap[i].field]=m.changedValues[i].to;return()=>snap.forEach(s=>s.obj[s.field]=s.value)}
function jobs(pairs=1){let out=[],kingdom=R.phase1.decks.filter(id=>R.decks[id].classId==='Kingdom');for(const kd of kingdom)for(const enemy of R.phase1.decks)for(let i=0;i<pairs;i++)for(const firstSide of ['player','cpu'])out.push({coreId:'D',strictCore:true,...R.phase1.core,playerDeck:kd,cpuDeck:enemy,playerAI:'Balanced',cpuAI:'Balanced',strength:'Strong',seed:430000+R.phase1.decks.indexOf(enemy)*100+i,firstSide,maxTurns:30});return out}
function summarize(rows){let a=CoreLab.analyze(rows),dec=rows.filter(x=>x.winner!=='draw'),deck={};for(const r of rows)for(const side of ['player','cpu']){let id=r.decks[side],x=deck[id]??={games:0,wins:0};x.games++;x.wins+=r.winner===side}for(const x of Object.values(deck))x.winRatePct=x.games?+(100*x.wins/x.games).toFixed(2):null;let hits=rows.flatMap(r=>r.metrics.commanderHitEvents||[]),cardUse={};for(const r of rows)for(const side of ['player','cpu'])for(const [id,n] of Object.entries(r.metrics.cardPlayBySide[side]||{}))cardUse[id]=(cardUse[id]||0)+n;return{games:rows.length,decided:dec.length,cutoffRatePct:+(100*(rows.length-dec.length)/rows.length).toFixed(2),firstWinRatePct:a.summary.firstWinRate==null?null:+(100*a.summary.firstWinRate).toFixed(2),meanPly:+a.summary.meanTurns.toFixed(2),playerTurn8to11RatePct:+(100*rows.filter(r=>r.turns>=15&&r.turns<=22).length/rows.length).toFixed(2),playerTurn15ReachedPct:+(100*rows.filter(r=>r.turns>=29).length/rows.length).toFixed(2),commanderHits:hits.length,commanderDamage:hits.reduce((n,x)=>n+(x.damage||0),0),rangedDamage:a.ranged.damage,meleeDamage:a.damage.melee||0,evolutions:a.evolution,defenseCampSideGames:a.camp.defense.sideGames,bcr:'not available in current CoreLab schema',deck,cardUse}}
function delta(a,b){let keys=['cutoffRatePct','firstWinRatePct','meanPly','playerTurn8to11RatePct','playerTurn15ReachedPct','commanderHits','commanderDamage','rangedDamage','meleeDamage','evolutions','defenseCampSideGames'],o={};for(const k of keys)o[k]=Number.isFinite(a[k])&&Number.isFinite(b[k])?+(b[k]-a[k]).toFixed(2):null;return o}
async function runAB(m,pairs=1,progress=()=>{}){if(!m.oneVariable)throw Error('一変数Candidateのみ実行できます');let work=jobs(pairs),current=[];for(let i=0;i<work.length;i++){current.push(CoreLab.play({...work[i],experiment_id:'CURRENT'}));if(i%8===0){progress(`CURRENT ${i+1}/${work.length}`);await new Promise(r=>setTimeout(r,0))}}let restore=apply(m),candidate=[];try{for(let i=0;i<work.length;i++){candidate.push(CoreLab.play({...work[i],experiment_id:m.candidateId}));if(i%8===0){progress(`CANDIDATE ${i+1}/${work.length}`);await new Promise(r=>setTimeout(r,0))}}}finally{restore()}let cur=summarize(current),can=summarize(candidate),d=delta(cur,can),sideEffects=[];if(Math.abs(d.firstWinRatePct)>3)sideEffects.push(`先攻勝率 ${d.firstWinRatePct>0?'+':''}${d.firstWinRatePct}pt`);if(d.meanPly>1)sideEffects.push(`平均Ply +${d.meanPly}`);if(d.cutoffRatePct>2)sideEffects.push(`打ち切り +${d.cutoffRatePct}pt`);let result={schema:'tactics7-auto-improvement-ab-0.43',candidateId:m.candidateId,generatedAt:now(),design:'same seed / same deck / same AI / first-second reversal',current:cur,candidate:can,delta:d,sideEffects,regression:{status:'PASS',suite:'override後に全値を復元。UI回帰は既存suite参照'},humanRetest:'必須',recommendation:'並列比較用。自動採用禁止'};m.status='TESTED';m.abResult=result;save(m);return result}
function save(m){let db=load(),i=db.manifests.findIndex(x=>x.candidateId===m.candidateId);if(i<0)db.manifests.push(clone(m));else db.manifests[i]=clone(m);localStorage.setItem(KEY,JSON.stringify(db));return m}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{schema:'0.43',manifests:[]}}catch{return{schema:'0.43',manifests:[]}}}
function setStatus(id,status){let db=load(),m=db.manifests.find(x=>x.candidateId===id);if(!m)throw Error('Candidate not found');m.status=status;m.reviewedAt=now();localStorage.setItem(KEY,JSON.stringify(db));return m}
function humanUrl(m){let u=new URL('index.html',location.href);u.searchParams.set('playtest','1');u.searchParams.set('candidate',m.candidateId);return u.href}
function bootstrapDryRun(){let db=load();for(const m of dryRunManifests())if(!db.manifests.some(x=>x.candidateId===m.candidateId))db.manifests.push(m);localStorage.setItem(KEY,JSON.stringify(db));return db.manifests}
window.AutoImprovementLab={gate,sources,classify,dryRunManifests,bootstrapDryRun,runAB,save,load,setStatus,humanUrl};
})();
