/* Public card inspection. Describes base card data separately from a live unit. */
(function(){'use strict';
const R=window.RULES,K=R.cards,C=R.classes;
const keywords={突進:'攻城研究カード限定。召喚ターンでも敵ユニットへ通常攻撃できる。移動・突撃・敵COMMANDERへの攻撃はできない。',押し出し:'隣接する敵を空いている1マス先へ動かす。移動先が塞がっていれば動かない。',引き寄せ:'射線上の敵を自分側へ1マス動かす。',位置交換:'指定した隣接味方2体の場所を入れ替える。',飛び越し:'隣接する敵ユニット1体を越え、反対側の空きマスへ移動する。',攻撃後移動:'攻撃後、空いている横のマスへ移る。',進化時移動:'進化効果で空き1マスへ動く。',進化時攻撃:'進化後に隣接敵へ1ダメージ。',疾走:'召喚ターンからCOMMANDERへ攻撃する能力。今回の攻城カードには存在しない。',防御:'次に受けるダメージを1軽減。',...(R.phase1?.keywords||{})};
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const evolution={step:'1マス移動',stepStrike:'1マス移動後、隣接敵へ1ダメージ',swap:'隣接味方と位置交換',push:'隣接敵を押し出す',shiftEnemy:'隣接敵を移動'};
function describe(id,unit=null){let card=K[id],cls=card?.type==='unit'?C[card.classId]:unit?C[unit.classId]:null;if(!card&&unit?.classId==='commander')card={name:'COMMANDER',type:'leader',tags:[],effect:'DOWNすると敗北',cost:null};if(!card&&unit?.classId==='lab_token')card={name:'仮トークン',type:'token',tags:[],effect:'生成されたユニット',cost:null};if(!card)return null;
 const abilities=[];if(card.type==='spell')abilities.push({timing:'使用時',text:card.effect||'効果なし'});else if(card.entryEffect||card.onSummon)abilities.push({timing:'登場時',text:card.effect||card.entryEffect||card.onSummon});if(card.rush)abilities.push({timing:'召喚ターン',text:keywords.突進});if(card.onAttack)abilities.push({timing:'攻撃後',text:card.onAttack==='push'?keywords.押し出し:keywords.攻撃後移動});if(card.onDown)abilities.push({timing:'DOWN時',text:card.onDown==='draw'?'カードを1枚引く':card.onDown});if(!abilities.length&&card.effect)abilities.push({timing:'常在・特性',text:card.effect});
 const shape=cls?.attackShape,dirs=shape?.directions==='orthogonal'?'縦横':shape?.directions==='diagonal'?'斜め':cls?.range?'縦横・斜め':'隣接8方向',movement=cls?.moveTrait?`隣接8方向1マス ＋ ${cls.moveTrait.type==='forward'?'前方':'縦横'}2マス`:'隣接8方向1マス';
 return{id,name:card.name,type:card.type,cost:card.cost,tags:card.tags||[],keywords:card.keywords||[],rarity:card.rarity||null,className:card.className||card.tags?.[0]||'Neutral',base:cls?{hp:cls.hp,melee:cls.melee,ranged:cls.ranged,range:cls.range,directions:dirs,movement,description:cls.description,unitPierce:shape?.unitPierce||0,terrainPierce:shape?.terrainPierce||0}:null,abilities,evolved:cls?{hp:cls.hp,melee:cls.melee,ranged:cls.ranged,range:cls.range,movement,directions:dirs,effect:evolution[cls.evolution]||cls.evolution||'なし',note:card.phase1?'進化で位置・射線・即時戦闘の役割が変化する。':'現行研究版では進化による基本数値の変更なし'}:null,current:unit?{hp:unit.hp,maxHp:unit.maxHp,guard:unit.guard,acted:unit.acted,sick:unit.sick,evolved:unit.evolved,state:unit.state,x:unit.x,y:unit.y,side:unit.side}:null,art:card.art||null}}
function render(id,unit=null,tab='normal'){let d=describe(id,unit);if(!d)return'<p>カード情報なし</p>';let evolved=tab==='evolved',b=evolved?d.evolved:d.base,parts=[];if(b)parts.push(`<dl><dt>HP</dt><dd>${b.hp}</dd><dt>近接</dt><dd>${b.melee}</dd>${b.range?`<dt>遠距離</dt><dd>${b.ranged}</dd><dt>射程</dt><dd>${b.range}</dd>`:''}<dt>攻撃方向</dt><dd>${esc(b.directions)}</dd><dt>移動</dt><dd>${esc(b.movement)}</dd>${b.unitPierce?`<dt>貫通</dt><dd>ユニット${b.unitPierce}体</dd>`:''}${b.terrainPierce?`<dt>障害物越え</dt><dd>${b.terrainPierce}個</dd>`:''}</dl>`);
 let ability=evolved?`<p><b>【進化時】</b>${esc(d.evolved?.effect||'なし')}</p><p>${esc(d.evolved?.note||'')}</p>`:d.abilities.map(a=>`<p><b>【${esc(a.timing)}】</b>${esc(a.text)}</p>`).join('');let current=d.current?`<section class="liveState"><strong>現在の盤面状態</strong><p>HP ${d.current.hp}/${d.current.maxHp} · ${d.current.state==='down'?'DOWN':d.current.state==='active'?'活動中':'撤退'} · ${d.current.evolved?'進化済み':'通常'}${d.current.guard?' · 防御 '+d.current.guard:''}${d.current.acted?' · 行動済み':''}${d.current.sick?' · 召喚ターン':''}</p></section>`:'';
 let artSrc=evolved?d.art?.evolved:d.art?.normal,portrait=artSrc?`<img src="${esc(artSrc)}" alt="${esc(d.name)}${evolved?'の進化後':''}イラスト">`:`<span aria-hidden="true">${esc(C[K[id]?.classId]?.icon||'✦')}</span>`;
 return `<div class="detailPortrait">${portrait}</div><h2>${esc(d.name)}</h2><div class="detailMeta">${d.cost==null?'デッキ外':`COST ${d.cost}`} · ${esc(d.className)} · ${esc(d.type)}${d.rarity?' · '+esc(d.rarity):''}${d.tags.length?' · '+d.tags.map(esc).join(' / '):''}</div>${current}${d.evolved?`<div class="detailTabs"><button data-card-tab="normal" class="${!evolved?'active':''}">通常</button><button data-card-tab="evolved" class="${evolved?'active':''}">進化後</button></div>`:''}<section class="baseStats"><strong>${evolved?'進化後の基本性能':'カード本来の基本性能'}</strong>${parts.join('')||'<p>数値なし</p>'}</section><section class="abilityText">${ability||'<p>追加能力なし</p>'}</section><div class="keywordHelp"><strong>関連キーワード</strong>${(d.keywords.length?d.keywords:Object.keys(keywords)).map(k=>`<button type="button" class="keyword" data-keyword="${esc(k)}" title="${esc(keywords[k]||'カード固有の用語')}">${esc(k)}</button>`).join('')}<p id="keywordExplanation" aria-live="polite">用語を押すと説明を表示します。</p></div>`}
window.CardCatalog={describe,render,keywords};
})();
