/* Ver.0.50 Human UX layer. Loads after deck_builder_v49.js; gameplay/data rules unchanged. */
(function(){'use strict';
const R=window.RULES,K=R.cards,C=R.classes,S=window.DeckStoreV49,$=id=>document.getElementById(id);
const CLS=['Kingdom','Forest','Arcane','Nether','Mechanica','Abyss'],JP={Kingdom:'王国',Forest:'森域',Arcane:'魔導',Nether:'冥界',Mechanica:'機巧',Abyss:'深淵'};
const TAG={Kingdom:'進軍と隊列',Forest:'機動と位置交換',Arcane:'射線と盤面操作',Nether:'墓地と復活',Mechanica:'Tokenと装置',Abyss:'代償と爆発力'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let edit=null,selected=null,tab='normal',mobile='pool',cpuIds=[],poolSort='cost',catalogSort='cost';
function modal(html){$('dialog').innerHTML=html;$('modal').hidden=false}
function head(title,back=lobby){return `<div class="v50head"><button class="v50back">← ${back===lobby?'ロビー':'戻る'}</button><h2>${title}</h2></div>`}
function bindBack(back=lobby){$('dialog').querySelector('.v50back').onclick=back}
function log(type,p={}){window.HumanPlaytest?.ui?.(type,p);let rows=[];try{rows=JSON.parse(localStorage.getItem(S.EVENTS)||'[]')}catch{}rows.push({type,timestamp:new Date().toISOString(),cardSetVersion:S.VERSION,...p});localStorage.setItem(S.EVENTS,JSON.stringify(rows.slice(-2000)))}
function lobby(){modal(`<div class="v50 lobby50"><div class="homeLogo">TACTICS <b>7</b><small>SET 1 PLAYTEST</small></div><p>デッキを組んで、7×7の戦場へ。</p><div class="lobbyActions"><button data-go="battle" class="primaryHome">対戦</button><button data-go="decks">デッキ</button><button data-go="cards">カード</button><button data-go="how">遊び方</button><button data-go="settings">設定</button></div><small>研究版 Ver.0.50</small></div>`);let go={battle, decks, cards, how, settings};$('dialog').querySelectorAll('[data-go]').forEach(b=>{b.onclick=()=>go[b.dataset.go]()})}
function decks(){let rows=S.read();modal(`<div class="v50">${head('マイデッキ')}<div class="deckToolbar"><button id="v50new" class="primaryHome">＋ 新しいデッキ</button><label class="fileButton">Import<input id="v50import" type="file" accept="application/json"></label></div><div class="deckGrid">${rows.length?rows.map(d=>{let v=S.validate(d);return `<article class="deckTile ${v.complete?'complete':'draft'}"><h3>${esc(d.name)}</h3><p>${JP[d.class]} · ${d.cards.length}/20 · ${v.complete?'対戦可能':'下書き'}</p><div><button data-edit="${d.deckId}">編集</button><button data-use="${d.deckId}" ${v.complete?'':'disabled'}>使う</button><button data-copy="${d.deckId}">複製</button><button data-delete="${d.deckId}">削除</button></div></article>`}).join(''):'<p class="emptyState">デッキを作成してください。</p>'}</div></div>`);bindBack();$('v50new').onclick=classes;$('v50import').onchange=async e=>{try{S.importData(await e.target.files[0].text());decks()}catch(x){alert(x.message)}};$('dialog').querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>open(S.read().find(d=>d.deckId===b.dataset.edit)));$('dialog').querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>battle(b.dataset.use));$('dialog').querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{S.duplicate(b.dataset.copy);decks()});$('dialog').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('このデッキを削除しますか？')){S.delete(b.dataset.delete);decks()}})}
function classes(){modal(`<div class="v50">${head('クラスを選択',decks)}<div class="classGrid49">${CLS.map(c=>`<button data-class="${c}"><b>${JP[c]}</b><small>${TAG[c]}</small><span>20種類</span></button>`).join('')}</div></div>`);bindBack(decks);$('dialog').querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>open({deckId:null,name:`${JP[b.dataset.class]}デッキ`,class:b.dataset.class,cardSetVersion:S.VERSION,cards:[]}))}
function open(d){edit={...d,cards:[...d.cards]};selected=selected&&S.eligible(selected,edit.class)?selected:R.set1Prototype.byClass[edit.class][0];tab='normal';builder()}
function sortCards(ids,mode='cost'){return [...ids].sort((a,b)=>{let ca=K[a],cb=K[b],cc=CLS.indexOf(S.cardClass(a))-CLS.indexOf(S.cardClass(b)),name=ca.name.localeCompare(cb.name,'ja');if(mode==='name')return name||ca.cost-cb.cost;if(mode==='class')return cc||ca.cost-cb.cost||name;return ca.cost-cb.cost||name})}
function summary(id){let c=K[id],u=c.type==='unit'?C[c.classId]:null,keys=(c.keywords||[]).slice(0,2).join('・');return `${u?`ATK ${u.melee} / HP ${u.hp}${u.range?` / 射程 ${u.range}`:''}`:'SPELL'}${keys?' · '+keys:''}`}
function cardRow(id,count,side='pool'){let c=K[id],full=count>=2;return `<article class="buildCard ${id===selected?'selected':''} ${full?'full':''}" data-card="${id}"><button class="cardSelect" data-select="${id}"><i>${c.cost}</i><b>${esc(c.name)}</b><small>${esc(summary(id))}</small></button><em>${count}/2</em><button class="${side==='pool'?'cardAdd':'cardRemove'}" data-${side==='pool'?'add':'remove'}="${id}" ${side==='pool'&&full?'disabled':''} aria-label="${side==='pool'?'追加':'削除'}">${side==='pool'?'+':'−'}</button></article>`}
function detail(id=selected){if(!id)return'<p>カードを選択してください。</p>';return `<div class="inlineDetailHead"><span>カード詳細</span><button data-detail-tab="normal" class="${tab==='normal'?'on':''}">通常</button><button data-detail-tab="evolved" class="${tab==='evolved'?'on':''}" ${K[id].type!=='unit'?'disabled':''}>進化後</button></div><div class="inlineCardDetail">${window.CardCatalog.render(id,null,tab)}</div>`}
function curve(){let s=S.stats(edit.cards),units=edit.cards.filter(id=>K[id].type==='unit'),ranged=units.filter(id=>C[K[id].classId]?.range>=2).length,melee=units.length-ranged;return `<div class="curve">${s.costs.map((n,i)=>n?`<span><b style="height:${Math.max(8,n*12)}px"></b><small>${i}:${n}</small></span>`:'').join('')}</div><p>平均COST ${s.average.toFixed(2)} · ユニット ${s.types.unit||0} · スペル ${s.types.spell||0} · 近接 ${melee} · 遠距離 ${ranged}</p><p>${Object.entries(s.roles).map(([k,n])=>`${k} ${n}`).join(' / ')}</p>`}
function builder(){let v=S.validate(edit),counts=v.counts;modal(`<div class="v50 builder50">${head('デッキ編集',decks)}<div class="builderTop"><input id="v50name" value="${esc(edit.name)}"><strong>${JP[edit.class]}</strong><span class="deckCount ${edit.cards.length===20?'ok':''}">${edit.cards.length}/20</span><button id="v50draft">下書き保存</button><button id="v50save" ${v.complete?'':'disabled'}>完成して保存</button></div><div class="mobileBuilderTabs"><button data-mobile="pool" class="${mobile==='pool'?'on':''}">カード</button><button data-mobile="deck" class="${mobile==='deck'?'on':''}">デッキ</button><button data-mobile="detail" class="${mobile==='detail'?'on':''}">詳細</button></div><div class="builder50grid show-${mobile}"><section class="poolPane"><div class="filters"><input id="v50search" placeholder="カード名・能力を検索"><select id="v50cost"><option value="">全COST</option><option>1-3</option><option>4-6</option><option>7-10</option></select><select id="v50type"><option value="">全種類</option><option value="unit">ユニット</option><option value="spell">スペル</option></select><select id="v50sort"><option value="cost" ${poolSort==='cost'?'selected':''}>COST順</option><option value="name" ${poolSort==='name'?'selected':''}>名前順</option><option value="class" ${poolSort==='class'?'selected':''}>クラス順</option></select></div><div id="v50pool" class="buildCards"></div></section><section class="deckPane">${curve()}<div class="buildCards">${Object.entries(counts).sort((a,b)=>K[a[0]].cost-K[b[0]].cost).map(([id,n])=>cardRow(id,n,'deck')).join('')}</div></section><aside class="detailPane">${detail()}</aside></div></div>`);bindBack(decks);bindBuilder();drawPool();bindCards();bindDetail()}
function drawPool(){let q=$('v50search').value.toLowerCase(),co=$('v50cost').value,ty=$('v50type').value,ids=R.set1Prototype.byClass[edit.class].filter(id=>(!q||`${K[id].name} ${K[id].effect||''} ${(K[id].keywords||[]).join(' ')}`.toLowerCase().includes(q))&&(!ty||K[id].type===ty)&&(!co||(co==='1-3'?K[id].cost<=3:co==='4-6'?K[id].cost>=4&&K[id].cost<=6:K[id].cost>=7)));$('v50pool').innerHTML=sortCards(ids,poolSort).map(id=>cardRow(id,edit.cards.filter(x=>x===id).length)).join('');bindCards()}
function select(id,source){selected=id;tab='normal';log('deckCardDetailView',{cardId:id,source,tab});$('dialog').querySelectorAll('.buildCard').forEach(x=>x.classList.toggle('selected',x.dataset.card===id));let p=$('dialog').querySelector('.detailPane');if(p){p.innerHTML=detail();bindDetail()}if(matchMedia('(max-width:900px)').matches){mobile='detail';$('dialog').querySelector('.builder50grid').className=`builder50grid show-detail`;$('dialog').querySelectorAll('[data-mobile]').forEach(x=>x.classList.toggle('on',x.dataset.mobile==='detail'))}}
function bindCards(){$('dialog').querySelectorAll('[data-select]').forEach(b=>{b.onclick=()=>select(b.dataset.select,b.closest('.deckPane')?'deck':'pool');b.ondblclick=()=>add(b.dataset.select)});$('dialog').querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();add(b.dataset.add)});$('dialog').querySelectorAll('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();remove(b.dataset.remove)})}
function add(id){let n=edit.cards.filter(x=>x===id).length;if(edit.cards.length>=20||n>=2)return;edit.cards.push(id);log('deckCardAdd',{cardId:id,count:n+1,deckId:edit.deckId});builder()}
function remove(id){let i=edit.cards.lastIndexOf(id);if(i<0)return;edit.cards.splice(i,1);log('deckCardRemove',{cardId:id,count:edit.cards.filter(x=>x===id).length,deckId:edit.deckId});builder()}
function bindDetail(){$('dialog').querySelectorAll('[data-detail-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.detailTab;log('deckCardDetailView',{cardId:selected,source:'detailTab',tab});$('dialog').querySelector('.detailPane').innerHTML=detail();bindDetail()});$('dialog').querySelectorAll('[data-keyword]').forEach(b=>b.onclick=()=>{$('dialog').querySelector('#keywordExplanation').textContent=window.CardCatalog.keywords[b.dataset.keyword]||'カード固有の用語'})}
function bindBuilder(){$('v50name').oninput=e=>edit.name=e.target.value;$('v50draft').onclick=()=>{edit=S.save(edit);decks()};$('v50save').onclick=()=>{edit=S.save(edit);decks()};for(const id of ['v50search','v50cost','v50type'])$(id).oninput=drawPool;$('v50sort').onchange=e=>{poolSort=e.target.value;drawPool()};$('dialog').querySelectorAll('[data-mobile]').forEach(b=>b.onclick=()=>{mobile=b.dataset.mobile;builder()})}
function battle(pre=''){let rows=S.read().filter(d=>S.validate(d,{requireComplete:true}).valid);modal(`<div class="v50 battle49">${head('対戦')}<label>自分のデッキ<select id="v50battle"><option value="">選択</option>${rows.map(d=>`<option value="${d.deckId}" ${d.deckId===pre?'selected':''}>${esc(d.name)}（${JP[d.class]}）</option>`).join('')}</select></label><label>相手<select id="v50cpu"><option value="random">おまかせ</option>${cpuIds.map(id=>`<option value="${id}">${esc(R.decks[id].name)}</option>`).join('')}</select></label><button id="v50start" class="primaryHome">対戦開始</button></div>`);bindBack();$('v50start').disabled=!pre;$('v50battle').onchange=e=>$('v50start').disabled=!e.target.value;$('v50start').onclick=()=>{let cpu=$('v50cpu').value;if(cpu==='random')cpu=cpuIds[Math.floor(Math.random()*cpuIds.length)];window.TacticsUI.start($('v50battle').value,cpu)}}
function cards(){let cl='Kingdom';modal(`<div class="v50 catalog50">${head('カード')}<div class="catalogTools"><div class="classTabs">${CLS.map(c=>`<button data-cl="${c}">${JP[c]}</button>`).join('')}</div><label>並び順 <select id="v50catalogSort"><option value="cost" ${catalogSort==='cost'?'selected':''}>COST順</option><option value="name" ${catalogSort==='name'?'selected':''}>名前順</option><option value="class" ${catalogSort==='class'?'selected':''}>クラス順</option></select></label></div><div class="catalog50grid"><div id="v50catalog" class="buildCards"></div><aside class="detailPane">${detail(R.set1Prototype.byClass[cl][0])}</aside></div></div>`);bindBack();let draw=()=>{$('v50catalog').innerHTML=sortCards(R.set1Prototype.byClass[cl],catalogSort).map(id=>cardRow(id,0)).join('');$('dialog').querySelectorAll('[data-add],[data-remove]').forEach(x=>x.remove());bindCards();bindDetail()};$('v50catalogSort').onchange=e=>{catalogSort=e.target.value;draw()};$('dialog').querySelectorAll('[data-cl]').forEach(b=>b.onclick=()=>{cl=b.dataset.cl;selected=sortCards(R.set1Prototype.byClass[cl],catalogSort)[0];draw()});selected=sortCards(R.set1Prototype.byClass[cl],catalogSort)[0];draw()}
function how(){modal(`<div class="v50 how50">${head('遊び方')}<section><h3>勝利条件</h3><strong>敵COMMANDERを倒せば勝利！</strong></section><ol><li>手札からカードを召喚</li><li>ユニットを移動</li><li>敵を攻撃</li><li>ENERGYは自分のPlayer Turnごとに増加</li><li>EPでユニットを進化</li><li>行動後はターン終了</li></ol><button id="v50rules">詳しいルール</button></div>`);bindBack();$('v50rules').onclick=rules}
function rules(){modal(`<div class="v50 rules50">${head('詳しいルール',how)}<dl><dt>召喚</dt><dd>手札のユニットを光る自陣マスへ置きます。</dd><dt>移動</dt><dd>ユニットは通常、隣接マスへ移動します。</dd><dt>突撃</dt><dd>1マス移動後、隣接する敵ユニットへ弱攻撃します。</dd><dt>G2R</dt><dd>突撃で敵をDOWNするとそのマスへ前進します。敵COMMANDER隣接では停止します。</dd><dt>遠距離</dt><dd>射程と射線を使い、離れた敵を攻撃します。</dd><dt>進化</dt><dd>EPを使い、移動・位置操作・即時戦闘などを得ます。</dd><dt>Token</dt><dd>カード効果で生成され、デッキには直接入れられません。</dd><dt>COMMANDER</dt><dd>HPが0になると敗北します。</dd><dt>デッキ</dt><dd>20枚。同名カードは最大2枚、単一クラスです。</dd></dl></div>`);bindBack(how)}
function settings(){let dev=new URLSearchParams(location.search).get('dev')==='1';modal(`<div class="v50 settings50">${head('設定')}<button id="v50lobby" class="primaryHome">ロビーに戻る</button><button id="v50guide">初心者ガイドをリセット</button>${dev?'<details><summary>開発 / 研究</summary><a href="core_lab.html">CORE LAB</a></details>':''}</div>`);bindBack();$('v50lobby').onclick=lobby;$('v50guide').onclick=()=>{localStorage.removeItem('tactics7_beginner_guide');alert('次の対戦で初心者ガイドを表示します。')}}
function init(){cpuIds=window.Set1Decks.install('v50cpu').ids;let q=new URLSearchParams(location.search),screen=q.get('v50screen');if(screen==='builder')open({deckId:null,name:'王国 QA',class:'Kingdom',cardSetVersion:S.VERSION,cards:S.suggested('Kingdom')});else if(screen==='cards')cards();else if(screen==='how')how();else if(screen==='settings')settings();else lobby()}
window.DeckBuilderV50={lobby,decks,classes,open,battle,cards,how,rules,settings,get editing(){return edit},get selected(){return selected}};init();
})();
