/* TACTICS 7 Ver.0.49 Lobby + Deck Builder. Research-only. */
(function(){'use strict';
const R=window.RULES,K=R.cards,VERSION='0.48-balance-prototype';
const STORE='tactics7_custom_decks_v049',EVENTS='tactics7_deck_events_v049';
const CLASSES=['Kingdom','Forest','Arcane','Nether','Mechanica','Abyss'];
const JP={Kingdom:'王国',Forest:'森域',Arcane:'魔導',Nether:'冥界',Mechanica:'機巧',Abyss:'深淵'};
const TAG={Kingdom:'進軍と隊列',Forest:'機動と位置交換',Arcane:'射線と盤面操作',Nether:'墓地と復活',Mechanica:'Tokenと装置',Abyss:'代償と爆発力'};
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const now=()=>new Date().toISOString(), uid=()=>`custom-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
function stableHash(cards){let counts={};for(const id of cards||[])counts[id]=(counts[id]||0)+1;let str=Object.keys(counts).sort().map(id=>`${id}:${counts[id]}`).join('|'),h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return `fnv1a-${(h>>>0).toString(16).padStart(8,'0')}`}
function cardClass(id){for(const cl of CLASSES)if(R.set1Prototype?.byClass?.[cl]?.includes(id))return cl;return null}
function eligible(id,cl){let c=K[id];return !!c&&cardClass(id)===cl&&c.deckEligible!==false&&!c.token&&!c.evolved&&!id.includes('_token')}
function validate(d,{requireComplete=false}={}){let errors=[],warnings=[],counts={};if(!d||typeof d!=='object')return{valid:false,complete:false,errors:['デッキ形式が不正です'],warnings};if(!CLASSES.includes(d.class))errors.push('クラスが不正です');if(d.cardSetVersion!==VERSION)errors.push(`カードセットVersionが違います（必要: ${VERSION}）`);if(!Array.isArray(d.cards))errors.push('cardsは配列である必要があります');for(const id of d.cards||[]){counts[id]=(counts[id]||0)+1;if(!eligible(id,d.class))errors.push(`${id}はこのデッキに入れられません`);if(counts[id]>2)errors.push(`${K[id]?.name||id}は3枚以上入れられません`)}let complete=(d.cards||[]).length===20&&!errors.length;if((d.cards||[]).length>20)errors.push('20枚を超えています');if(requireComplete&&!complete)errors.push('対戦には20枚ちょうど必要です');if(!complete&&!requireComplete)warnings.push(`下書き: ${(d.cards||[]).length}/20枚`);return{valid:!errors.length&&(!requireComplete||complete),complete,errors:[...new Set(errors)],warnings,counts}}
function read(){try{let x=JSON.parse(localStorage.getItem(STORE)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function install(d){let v=validate(d,{requireComplete:true});if(!v.valid)return false;R.decks[d.deckId]={name:d.name,classId:d.class,cards:[...d.cards],isCustom:true,set1Research:true,deckHash:stableHash(d.cards),cardSetVersion:d.cardSetVersion};return true}
function installAll(){for(const d of read())install(d)}
function write(rows){localStorage.setItem(STORE,JSON.stringify(rows));installAll()}
function record(type,payload={}){let rows=[];try{rows=JSON.parse(localStorage.getItem(EVENTS)||'[]')}catch{}rows.push({eventId:uid(),type,timestamp:now(),cardSetVersion:VERSION,...payload});localStorage.setItem(EVENTS,JSON.stringify(rows.slice(-2000)));window.HumanPlaytest?.ui?.('deckConstruction',{type,...payload})}
function save(input){let rows=read(),old=rows.find(x=>x.deckId===input.deckId),d={deckId:input.deckId||uid(),name:(input.name||'名称未設定デッキ').trim().slice(0,40),class:input.class,cardSetVersion:VERSION,cards:[...(input.cards||[])],createdAt:old?.createdAt||input.createdAt||now(),updatedAt:now()};let v=validate(d);if(!v.valid)throw Error(v.errors.join('\n'));let i=rows.findIndex(x=>x.deckId===d.deckId);if(i<0)rows.push(d);else rows[i]=d;write(rows);record(old?'deck_update':'deck_create',{deckId:d.deckId,deckHash:stableHash(d.cards),classId:d.class,count:d.cards.length});return d}
function remove(id){let d=read().find(x=>x.deckId===id);write(read().filter(x=>x.deckId!==id));delete R.decks[id];record('deck_delete',{deckId:id,deckHash:d&&stableHash(d.cards)});return !!d}
function duplicate(id){let d=read().find(x=>x.deckId===id);if(!d)return null;return save({...d,deckId:uid(),name:`${d.name} コピー`,createdAt:null})}
function exportDeck(id){let d=read().find(x=>x.deckId===id);if(!d)throw Error('デッキが見つかりません');download({schema:'tactics7-deck-0.49',deck:d},`${d.name}.t7deck.json`);record('deck_export',{deckId:id})}
function importData(raw){let data=typeof raw==='string'?JSON.parse(raw):raw,d=data?.deck||data,clean={...d,deckId:uid(),cardSetVersion:d.cardSetVersion};let v=validate(clean);if(!v.valid)throw Error(v.errors.join('\n'));record('deck_import',{sourceDeckId:d.deckId,classId:d.class,count:d.cards.length});return save(clean)}
function download(data,name){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function stats(cards){let costs=Array(11).fill(0),types={unit:0,spell:0},roles={};for(const id of cards){let c=K[id];costs[Math.min(10,c.cost||0)]++;types[c.type]=(types[c.type]||0)+1;roles[c.role||'other']=(roles[c.role||'other']||0)+1}return{costs,types,roles,average:cards.length?cards.reduce((n,id)=>n+(K[id].cost||0),0)/cards.length:0}}
function suggested(cl){let pool=R.set1Prototype.byClass[cl],cards=[];for(const band of [[1,3,8],[4,6,8],[7,10,4]])for(const id of pool.filter(id=>K[id].cost>=band[0]&&K[id].cost<=band[1]).sort((a,b)=>K[a].cost-K[b].cost).slice(0,band[2]/2))cards.push(id,id);for(const id of pool)while(cards.length<20&&cards.filter(x=>x===id).length<2)cards.push(id);return cards.slice(0,20)}
const Store={VERSION,STORE,EVENTS,read,save,delete:remove,duplicate,validate,stableHash,eligible,cardClass,installAll,importData,exportDeck,stats,suggested,events:()=>{try{return JSON.parse(localStorage.getItem(EVENTS)||'[]')}catch{return[]}}};
window.DeckStoreV49=Store;

let cpuIds=[],editing=null,mobileTab='pool';
function modal(html){$('dialog').innerHTML=html;$('modal').hidden=false}
function backButton(title){return `<div class="v49head"><button data-v49-back aria-label="戻る">←</button><h2>${title}</h2></div>`}
function renderLobby(){modal(`<div class="v49 lobby49"><div class="homeLogo">TACTICS <b>7</b><small>SET 1 PLAYTEST</small></div><p>デッキを組んで、7×7の戦場へ。</p><div class="lobbyActions"><button data-nav="battle" class="primaryHome">対戦</button><button data-nav="decks">デッキ</button><button data-nav="cards">カード</button><button data-nav="how">遊び方</button><button data-nav="settings">設定</button></div><small>研究版 Ver.0.49 / データはこの端末に保存されます</small></div>`);$('dialog').querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>({battle:renderBattle,decks:renderDecks,cards:renderCards,how:()=>window.TacticsUI.showDeck(),settings:()=>window.TacticsUI.showSettings()}[b.dataset.nav]||renderLobby)())}
function renderDecks(){let rows=read();modal(`<div class="v49 decks49">${backButton('マイデッキ')}<div class="deckToolbar"><button id="newDeck" class="primaryHome">＋ 新しいデッキ</button><label class="fileButton">Import<input id="deckImport" type="file" accept="application/json"></label></div><div class="deckGrid">${rows.length?rows.map(d=>{let v=validate(d);return `<article class="deckTile ${v.complete?'complete':'draft'}"><h3>${esc(d.name)}</h3><p>${JP[d.class]} · ${d.cards.length}/20</p><small>${v.complete?'対戦可能':'下書き'} · ${stableHash(d.cards)}</small><div><button data-use="${d.deckId}" ${v.complete?'':'disabled'}>使う</button><button data-edit="${d.deckId}">編集</button><button data-copy="${d.deckId}">複製</button><button data-export="${d.deckId}">Export</button><button data-delete="${d.deckId}">削除</button></div></article>`}).join(''):'<p class="emptyState">まだデッキがありません。最初のデッキを作りましょう。</p>'}</div></div>`);bindBack(renderLobby);$('newDeck').onclick=renderClassPicker;$('deckImport').onchange=async e=>{try{importData(await e.target.files[0].text());renderDecks()}catch(err){alert(`Importできません: ${err.message}`)}};bindDeckActions()}
function bindDeckActions(){let q=(s,f)=>$('dialog').querySelectorAll(s).forEach(b=>b.onclick=f);q('[data-edit]',e=>openBuilder(read().find(x=>x.deckId===e.currentTarget.dataset.edit)));q('[data-copy]',e=>{duplicate(e.currentTarget.dataset.copy);renderDecks()});q('[data-export]',e=>exportDeck(e.currentTarget.dataset.export));q('[data-delete]',e=>{if(confirm('このデッキを削除しますか？')){remove(e.currentTarget.dataset.delete);renderDecks()}});q('[data-use]',e=>renderBattle(e.currentTarget.dataset.use))}
function renderClassPicker(){modal(`<div class="v49">${backButton('クラスを選択')}<div class="classGrid49">${CLASSES.map(cl=>`<button data-class="${cl}"><b>${JP[cl]}</b><small>${TAG[cl]}</small><span>20種類</span></button>`).join('')}</div></div>`);bindBack(renderDecks);$('dialog').querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>openBuilder({deckId:null,name:`${JP[b.dataset.class]}デッキ`,class:b.dataset.class,cardSetVersion:VERSION,cards:[],createdAt:null}))}
function openBuilder(d){editing={...d,cards:[...d.cards]};renderBuilder()}
function cardText(id){let c=K[id];return `${c.name} ${c.effect||''} ${(c.keywords||[]).join(' ')}`.toLowerCase()}
function renderBuilder(){let d=editing,s=stats(d.cards),v=validate(d),counts=v.counts,pool=R.set1Prototype.byClass[d.class];modal(`<div class="v49 builder49">${backButton('デッキ編集')}<div class="builderTop"><input id="deckName" value="${esc(d.name)}" maxlength="40"><strong>${JP[d.class]}</strong><button id="changeClass">クラス変更</button><span class="deckCount ${d.cards.length===20?'ok':''}">${d.cards.length}/20</span><button id="saveDraft">下書き保存</button><button id="saveDeck" ${v.complete?'':'disabled'}>完成して保存</button><button id="builderExport">Export</button></div><div class="mobileBuilderTabs"><button data-tab="pool" class="${mobileTab==='pool'?'on':''}">カード</button><button data-tab="deck" class="${mobileTab==='deck'?'on':''}">デッキ ${d.cards.length}/20</button></div><div class="builderColumns ${mobileTab==='deck'?'showDeckTab':'showPoolTab'}"><section class="poolPane"><div class="filters"><input id="cardSearch" placeholder="カード名・能力を検索"><select id="costFilter"><option value="">全COST</option><option value="1-3">1〜3</option><option value="4-6">4〜6</option><option value="7-10">7〜10</option></select><select id="typeFilter"><option value="">全種類</option><option value="unit">ユニット</option><option value="spell">スペル</option></select><select id="sortCards"><option value="cost">COST順</option><option value="name">名前順</option></select></div><div id="poolCards" class="poolCards"></div></section><section class="deckPane"><div class="curve">${s.costs.map((n,i)=>n?`<span><b style="height:${Math.max(8,n*12)}px"></b><small>${i}:${n}</small></span>`:'').join('')}</div><p>平均COST ${s.average.toFixed(2)} · ユニット ${s.types.unit||0} · スペル ${s.types.spell||0}</p><p class="mechanicStats">${Object.entries(s.roles).map(([k,n])=>`${esc(k)} ${n}`).join(' / ')||'カードを追加してください'}</p><div id="deckCards" class="deckCards">${Object.entries(counts).sort((a,b)=>K[a[0]].cost-K[b[0]].cost).map(([id,n])=>miniCard(id,n,'remove')).join('')}</div></section></div></div>`);bindBack(()=>{if(confirm('編集内容を閉じますか？'))renderDecks()});bindBuilder();filterPool()}
function miniCard(id,n,action){let c=K[id];return `<button class="miniCard" data-${action}="${id}" data-detail="${id}"><i>${c.cost}</i><b>${esc(c.name)}</b><small>${c.type==='unit'?'UNIT':'SPELL'} · ${esc(c.role||'')}</small>${n!=null?`<em>${n}/2</em>`:''}<span class="cardInfo" data-info="${id}">詳細</span></button>`}
function bindBuilder(){let d=editing;$('deckName').oninput=e=>d.name=e.target.value;$('changeClass').onclick=()=>{if(!d.cards.length||confirm('クラスを変更すると現在のカードをすべて外します。'))renderClassPicker()};$('saveDraft').onclick=()=>{d=save(d);editing=d;renderDecks()};$('saveDeck').onclick=()=>{d=save(d);record('deck_complete',{deckId:d.deckId,deckHash:stableHash(d.cards)});editing=d;renderDecks()};$('builderExport').onclick=()=>{let saved=d.deckId?save(d):save(d);editing=saved;exportDeck(saved.deckId)};$('dialog').querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{mobileTab=b.dataset.tab;renderBuilder()});for(const id of ['cardSearch','costFilter','typeFilter','sortCards'])$(id).oninput=filterPool;bindCardButtons()}
function filterPool(){let query=$('cardSearch').value.trim().toLowerCase(),cost=$('costFilter').value,type=$('typeFilter').value,sort=$('sortCards').value,ids=R.set1Prototype.byClass[editing.class].filter(id=>eligible(id,editing.class)).filter(id=>!query||cardText(id).includes(query)).filter(id=>!type||K[id].type===type).filter(id=>!cost||(cost==='1-3'?K[id].cost<=3:cost==='4-6'?K[id].cost>=4&&K[id].cost<=6:K[id].cost>=7));ids.sort(sort==='name'?(a,b)=>K[a].name.localeCompare(K[b].name,'ja'):(a,b)=>K[a].cost-K[b].cost||K[a].name.localeCompare(K[b].name,'ja'));$('poolCards').innerHTML=ids.map(id=>miniCard(id,(editing.cards.filter(x=>x===id).length),'add')).join('');bindCardButtons()}
function bindCardButtons(){$('dialog').querySelectorAll('[data-info]').forEach(x=>x.onclick=e=>{e.stopPropagation();showCard(x.dataset.info)});$('dialog').querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-info]')||e.altKey||e.metaKey)return showCard(b.dataset.add);let id=b.dataset.add;if(editing.cards.length<20&&editing.cards.filter(x=>x===id).length<2){editing.cards.push(id);record('card_add',{deckId:editing.deckId,cardId:id,count:editing.cards.filter(x=>x===id).length});renderBuilder()}else alert('20枚まで・同名2枚までです')});$('dialog').querySelectorAll('[data-remove]').forEach(b=>b.onclick=e=>{if(e.target.closest('[data-info]')||e.altKey||e.metaKey)return showCard(b.dataset.remove);let id=b.dataset.remove,i=editing.cards.lastIndexOf(id);if(i>=0){editing.cards.splice(i,1);record('card_remove',{deckId:editing.deckId,cardId:id});renderBuilder()}});$('dialog').querySelectorAll('.miniCard').forEach(b=>b.oncontextmenu=e=>{e.preventDefault();showCard(b.dataset.detail)})}
function showCard(id){$('cardDetailContent').innerHTML=window.CardCatalog.render(id,null,'normal');$('cardDetailPanel').hidden=false}
function renderBattle(preselect=''){let rows=read().filter(d=>validate(d,{requireComplete:true}).valid);modal(`<div class="v49 battle49">${backButton('対戦')}<label>自分のデッキ<select id="battleDeck"><option value="">選択してください</option>${rows.map(d=>`<option value="${d.deckId}" ${d.deckId===preselect?'selected':''}>${esc(d.name)}（${JP[d.class]}）</option>`).join('')}</select></label><label>CPU<select id="cpuDeck"><option value="random">おまかせ</option>${cpuIds.map(id=>`<option value="${id}">${esc(R.decks[id].name)}</option>`).join('')}</select></label><div id="battleSummary"></div><button id="battleStart" class="primaryHome">対戦開始</button>${rows.length?'':'<p>先に完成デッキを作ってください。</p><button id="goDecks">デッキを作る</button>'}</div>`);bindBack(renderLobby);let update=()=>{let d=read().find(x=>x.deckId===$('battleDeck').value);$('battleSummary').textContent=d?`${d.name} / ${JP[d.class]} / 20枚`:'完成デッキを選択してください';$('battleStart').disabled=!d};$('battleDeck').onchange=update;update();$('battleStart').onclick=()=>{let own=$('battleDeck').value,cpu=$('cpuDeck').value;if(cpu==='random')cpu=cpuIds[Math.floor(Math.random()*cpuIds.length)];record('deck_battle_start',{deckId:own,deckHash:R.decks[own]?.deckHash,cpuDeckId:cpu});window.TacticsUI.start(own,cpu)};if($('goDecks'))$('goDecks').onclick=renderDecks}
function renderCards(){let cl=CLASSES[0];modal(`<div class="v49 catalog49">${backButton('カード')}<div class="classTabs">${CLASSES.map(x=>`<button data-catalog-class="${x}" class="${x===cl?'on':''}">${JP[x]}</button>`).join('')}</div><div id="catalogCards" class="poolCards"></div></div>`);bindBack(renderLobby);let draw=()=>{$('catalogCards').innerHTML=R.set1Prototype.byClass[cl].map(id=>miniCard(id,null,'view')).join('');$('dialog').querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showCard(b.dataset.view))};$('dialog').querySelectorAll('[data-catalog-class]').forEach(b=>b.onclick=()=>{cl=b.dataset.catalogClass;$('dialog').querySelectorAll('[data-catalog-class]').forEach(x=>x.classList.toggle('on',x===b));draw()});draw()}
function bindBack(fn){$('dialog').querySelector('[data-v49-back]').onclick=fn}
function initial(){let q=new URLSearchParams(location.search),screen=q.get('v49screen'),cl=CLASSES.includes(q.get('v49class'))?q.get('v49class'):'Kingdom';if(screen==='builder')openBuilder({deckId:null,name:`${JP[cl]} QA`,class:cl,cardSetVersion:VERSION,cards:suggested(cl),createdAt:null});else if(screen==='decks')renderDecks();else if(screen==='cards')renderCards();else renderLobby()}
function init(){if(!R.set1Prototype||R.set1Prototype.version!==VERSION)return console.error('Ver.0.49 requires Ver.0.48 Set 1');Store.installAll();cpuIds=window.Set1Decks.install('v49cpu').ids;if(window.TACTICS7_GAME_VERSION!=='0.49')return;let obs=new MutationObserver(()=>{let home=$('dialog')?.querySelector('.homeScreen:not(.idGate):not(.consentScreen)');if(home&&!home.closest('.v49')){obs.disconnect();initial();obs.observe($('dialog'),{childList:true,subtree:true})}});obs.observe($('dialog'),{childList:true,subtree:true});if($('dialog')?.querySelector('.homeScreen:not(.idGate):not(.consentScreen)'))initial()}
window.DeckBuilderV49={init,renderLobby,renderDecks,renderBattle,renderCards,openBuilder,get editing(){return editing}};
init();
})();
