/* Ver.0.42 Human Auto Report renderer. */
(function(){'use strict';
const esc=s=>String(s??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const p=v=>Number.isFinite(v)?v.toFixed(1)+'%':'—', n=v=>Number.isFinite(v)?v:'—';
const cards=()=>window.RULES?.cards||{};
function candidateBlock(title,rows){return `<section><h3>${title}</h3>${rows.length?rows.map(x=>`<article class="candidate ${x.priority.toLowerCase()}"><b>${esc(x.priority)} · ${esc(x.title)}</b><small>${esc(x.confidence)} · ${esc(x.evidence)}</small></article>`).join(''):'<p class="muted">現在の標本では候補なし</p>'}</section>`}
function table(headers,rows){return `<div class="tableWrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function render(r){let c=r.core,s=r.survey,classes=Object.entries(c.byClass),decks=Object.entries(c.byDeck),details=Object.entries(r.cardDetail).sort((a,b)=>b[1].opens-a[1].opens),times=Object.entries(r.decisionTime.byAction).sort((a,b)=>(b[1].medianMs||0)-(a[1].medianMs||0));
 return `<div class="autoReport"><header><p class="eyebrow">TACTICS 7 HUMAN PLAYTEST</p><h2>Human Auto Report</h2><p>${esc(r.generatedAt)} · ${esc(r.schema)}</p>${r.sampleWarning?`<div class="sampleWarning">⚠ ${esc(r.sampleWarning)}</div>`:''}</header>
 <div class="kpis">${[['有効試合',c.validMatches],['Tester',c.testers],['楽しさ',s.fun.mean==null?'—':s.fun.mean+'/5'],['分かりやすさ',s.clarity.mean==null?'—':s.clarity.mean+'/5'],['Play Again',p(s.playAgain.ratePct)],['人間勝率',p(c.human.ratePct)],['先攻時勝率',p(c.first.first?.ratePct)],['Player Turn 8〜11',p(c.playerTurn8to11.ratePct)]].map(([a,b])=>`<div><small>${a}</small><strong>${b}</strong></div>`).join('')}</div>
 <div class="candidateGrid">${candidateBlock('Balance Candidates',r.candidates.balance)}${candidateBlock('AI Candidates',r.candidates.ai)}${candidateBlock('UX Candidates',r.candidates.ux)}${candidateBlock('Fun Candidates',r.candidates.fun)}</div>
 <details open><summary>Human vs AI · クラス</summary>${table(['クラス','Human','試合','Tester均等','AI','差','確度'],classes.map(([id,x])=>[esc(window.RULES?.phase1?.identities?.[id]?.name||id),`${x.wins}/${x.games} (${p(x.ratePct)})`,x.games,p(x.testerBalancedWinRatePct),p(x.aiWinRatePct),Number.isFinite(x.differencePctPoints)?`${x.differencePctPoints>0?'+':''}${x.differencePctPoints}pt`:'—',esc(x.confidence)]))}<p class="muted">AI行動ログがない指標は推測せず、比較データなしとして扱います。</p></details>
 <details><summary>デッキ・Tester偏り</summary>${table(['デッキ','Human勝率','試合','Tester均等','確度'],decks.map(([id,x])=>[esc(window.RULES?.decks?.[id]?.name||id),`${x.wins}/${x.games} (${p(x.ratePct)})`,x.games,p(x.testerBalancedWinRatePct),esc(x.confidence)]))}<p>全体：match weighted ${p(c.matchWeightedWinRatePct)} / tester balanced ${p(c.testerBalanced.winRatePct)}</p>${table(['Tester','試合','勝率'],Object.entries(c.byTester||{}).map(([id,x])=>[esc(id),x.games,p(x.ratePct)]))}</details>
 <details><summary>Decision Time・操作</summary><p>中央値 ${n(r.decisionTime.all.medianMs)}ms / P75 ${n(r.decisionTime.all.p75Ms)}ms / P90 ${n(r.decisionTime.all.p90Ms)}ms / 放置疑い除外 ${r.decisionTime.excludedOver60s}</p>${table(['行動','件数','中央値','P75','P90'],times.map(([id,x])=>[esc(id),x.count,n(x.medianMs),n(x.p75Ms),n(x.p90Ms)]))}<p>召喚：drag ${r.summon.drag} / click ${r.summon.click} · Cancel ${r.cancel.cancel} / Drag Cancel ${r.cancel.dragCancel}</p></details>
 <details><summary>遠距離・進化・カード詳細</summary><p>人間の遠距離後列召喚 ${r.ranged.back}/${r.ranged.summons} (${p(r.aiComparison.ranged.humanBackRowRatePct)}) · AI後列率：比較データなし</p><p>進化対象：${Object.entries(r.evolution.targets).map(([id,x])=>`${esc(cards()[id]?.name||id)} ${x.uses}`).join(' / ')||'—'}</p>${table(['カード','詳細閲覧','対象試合','1試合あたり','使用前','進化後タブ'],details.map(([id,x])=>[esc(x.cardName),x.opens,x.matches,x.perMatch,x.beforeUse,x.evolvedTab]))}</details>
 <details><summary>アンケート原文</summary><p>回答 ${s.responses} · Play Again ${s.playAgain.yes}/${s.playAgain.total}</p>${s.comments.length?table(['クラス','勝敗','強弱報告','コメント'],s.comments.map(x=>[esc(x.classId),x.won?'勝':'負',esc(x.balanceCard),esc(x.comment)])):'<p class="muted">コメントなし</p>'}</details>
 <details><summary>測定限界</summary><ul>${r.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details></div>`}
window.HumanAutoReportUI={render};
})();
