/* Ver.0.13: disposable siege environment. The 177-card pool and Core D stay intact. */
(function(){'use strict';
const R=window.RULES,K=R.cards,classes=['Kingdom','Forest','Arcane','Nether','Mechanica','Abyss'];
const plans={
 Kingdom:[['u',1,0,'advance','前進し、突進で前衛に即応',1],['u',2,1,'guardAdjacent','隊列を守る突進兵',1],['u',3,2,'pushEnemy','登場時に隣接敵を押す',0],['u',4,3,'advance','攻撃後に敵を押す突破兵',0,'push'],['s',1,0,'push','隣接した敵を1マス押す'],['s',3,0,'breach','隣接する敵ユニットを押し、味方が元のマスへ進入']],
 Forest:[['u',1,0,'advance','登場時1マス前進'],['u',2,1,'swapAdjacent','登場時に隣接味方と交換'],['u',3,2,'advance','前方へ進む機動兵'],['u',4,3,'draw','攻撃後に横へ離脱',0,'sidestep'],['s',1,0,'swap','隣接味方を入れ替える'],['s',3,0,'vault','味方が隣接する1体を飛び越え、空きマスへ移動']],
 Arcane:[['u',1,0,'draw','登場時1ドロー'],['u',2,1,'pushEnemy','隣接敵を押す'],['u',3,2,'pullEnemy','2マス先の敵を引く'],['u',4,3,'pushEnemy','射線を開く術兵'],['s',1,0,'push','隣接敵を1マス押す'],['s',3,0,'pull','2マス先の敵を1マス引く']],
 Nether:[['u',1,0,'drawIfGrave','墓地があれば1ドロー'],['u',2,1,'reanimate','低コストユニットを復帰'],['u',3,2,'drawIfGrave','突進。墓地があればドロー',1],['u',4,3,'reanimate','進化時に敵を押す'],['s',1,0,'rescue','DOWNした味方を復帰'],['s',3,0,'reanimate','墓地の低コストユニットを復帰']],
 Mechanica:[['u',1,0,'token','隣接マスへトークン'],['u',2,1,'guardAdjacent','隣接味方に防御'],['u',3,2,'pushEnemy','隣接敵を押す'],['u',4,3,'token','トークンで挟撃'],['s',1,0,'token','味方の隣にトークンを生成'],['s',3,0,'barrage','隣接敵に1ダメージ。生存すれば1マス押す']],
 Abyss:[['u',1,0,'selfHarmAdvance','自リーダー1ダメージで前進',1],['u',2,1,'selfHarmDraw','自リーダー1ダメージでドロー',1],['u',3,2,'drain','隣接敵を傷つけ回復。突進',1],['u',4,3,'selfHarmAdvance','自傷して前進'],['s',1,0,'selfHarmRush','自傷して味方を前進'],['s',3,0,'bloodLunge','自リーダー1ダメージを代償に味方を直線2マス進める']]
};
const ids=[],byClass={};for(const cls of classes){byClass[cls]=[];plans[cls].forEach(([type,cost,tier,effect,description,rush=0,onAttack=null],i)=>{let id=`SIEGE_${cls}_${String(i+1).padStart(2,'0')}`,unit=type==='u';K[id]={name:id,type:unit?'unit':'spell',classId:unit?`lab_${cls}_${tier}`:undefined,cost,tags:[cls,'Siege'],className:cls,archetype:'Siege',effect:description,entryEffect:unit?effect:null,spellKind:unit?null:effect,rush:!!rush,onAttack,art:{normal:null,evolved:null}};ids.push(id);byClass[cls].push(id)})}
const decks=[],paired={},densityDecks={low:[],medium:[],high:[]};for(const sourceId of R.research.decks){let source=R.decks['dcgsafe_'+sourceId],cls=source.classId,base=source.cards.slice(),siege=byClass[cls];if(!siege)continue;let replace=[];for(const id of siege){let c=K[id],at=base.findIndex((old,i)=>!replace.some(r=>r.index===i)&&K[old].type===c.type&&K[old].cost===c.cost);if(at<0)throw Error('No same-cost replacement '+sourceId+' '+id);replace.push({index:at,from:base[at],to:id});base[at]=id}let id='siege_'+sourceId;R.decks[id]={...source,name:source.name+' / 攻城',description:'Core D2研究用。元デッキの同種・同コスト6枚を攻城カードへ置換',cards:base,siegeCards:siege.slice()};let v=R.validateDeck(base,cls);if(!v.ok)throw Error(id+' '+v.reason);decks.push(id);densityDecks.medium.push(id);paired[id]={control:'dcgsafe_'+sourceId,replacements:replace};
 for(const density of ['low','high']){let variant=source.cards.slice(),selected=density==='low'?[replace[1],replace[5]]:replace;for(const r of selected)variant[r.index]=r.to;if(density==='high')for(const siegeId of siege.slice(0,4)){let c=K[siegeId],at=variant.findIndex((old,i)=>!selected.some(r=>r.index===i)&&K[old].type===c.type&&K[old].cost===c.cost&&old!==siegeId);if(at<0)throw Error('No high density slot '+sourceId+' '+siegeId);variant[at]=siegeId}let variantId=`siege_${density}_${sourceId}`;R.decks[variantId]={...source,name:source.name+` / 攻城${density}`,description:`Core D2攻城カード密度${density}`,cards:variant};let valid=R.validateDeck(variant,cls);if(!valid.ok)throw Error(variantId+' '+valid.reason);densityDecks[density].push(variantId)}}
const defenderSources={Fortress:'lab_Mechanica_Fortification',Control:'lab_Arcane_Control',RangedDefense:'lab_Arcane_Position',TokenDefense:'lab_Mechanica_Token'};const defenderDecks=[];for(const [name,sourceId] of Object.entries(defenderSources)){let source=R.decks['dcgsafe_'+sourceId],id='siege_defense_'+name;R.decks[id]={...source,name:`防衛試験 / ${name}`,description:'攻城デッキへの防衛対照。中央非依存の既存カード20枚',cards:source.cards.slice()};defenderDecks.push(id)}
R.research.siegeCards=ids;R.research.siegeDecks=decks;window.SiegeLab={version:'0.13',classes,ids,byClass,decks,paired,densityDecks,defenderDecks,plans};
})();
