/* CORE LAB AI. Personality weights and search strength are independent. */
(function(){'use strict';
const R=window.RULES,K=R.cards,C=R.classes;
const D=(a,b)=>Math.max(Math.abs(a.x-b.x),Math.abs(a.y-b.y));
const enemy=s=>s==='player'?'cpu':'player';
const W={Balanced:{center:5,forward:2,attack:5,defense:5,ranged:4,energy:3,evolve:3},Aggro:{center:3,forward:7,attack:8,defense:2,ranged:1,energy:5,evolve:2},Tempo:{center:4,forward:3,attack:7,defense:4,ranged:3,energy:7,evolve:4},Control:{center:3,forward:0,attack:6,defense:9,ranged:5,energy:4,evolve:4},Center:{center:12,forward:1,attack:4,defense:3,ranged:2,energy:5,evolve:3},CommanderRush:{center:1,forward:10,attack:11,defense:2,ranged:2,energy:4,evolve:3},Tactical:{center:6,forward:4,attack:6,defense:6,ranged:6,energy:4,evolve:3},Evolution:{center:4,forward:2,attack:5,defense:5,ranged:3,energy:3,evolve:10},Ranged:{center:3,forward:0,attack:7,defense:6,ranged:12,energy:3,evolve:3},Melee:{center:4,forward:8,attack:8,defense:3,ranged:0,energy:4,evolve:3}};
function context(g,s){let us=g.units.filter(u=>u.side===s&&u.state==='active'),them=g.units.filter(u=>u.side!==s&&u.state==='active');return{us,them,cmd:them.find(u=>u.classId==='commander'),own:us.find(u=>u.classId==='commander')}}
function danger(g,u,at,them){let fake={...u,x:at.x,y:at.y},n=0;for(const v of them)if(g.attackInfo(v,fake))n+=C[v.classId].range?C[v.classId].ranged:C[v.classId].melee;return n}
function position(g,u,p,ctx,w){let oldCenter=D(u,R.center),newCenter=D(p,R.center),oldCmd=D(u,ctx.cmd),newCmd=D(p,ctx.cmd),nearest=Math.min(7,...ctx.them.map(v=>D(p,v))),ranged=C[u.classId].range>1;let centerWeight=g.config.centerEnabled?w.center:0,score=(oldCenter-newCenter)*centerWeight+(oldCmd-newCmd)*w.forward;score+=(newCenter===0?9:0)*centerWeight/5;if(u.classId==='commander')score-=danger(g,u,p,ctx.them)*w.defense*2+(newCmd<oldCmd?6:0);else score-=danger(g,u,p,ctx.them)*w.defense*(ranged?.8:.35);if(ranged){score+=(nearest>=2&&nearest<=C[u.classId].range?w.ranged:0);if(nearest===1)score-=w.ranged*3}else if(nearest===1)score+=w.attack;return score}
function candidates(g,s,personality='Balanced',strength='Strong'){
 const w=W[personality]||W.Balanced,ctx=context(g,s),out=[],p=g.sides[s];
 if(g.pending){for(const opt of g.pending.options){let h=clone(g),before=value(h,s);h.resolvePending(opt);let unit=g.units.find(u=>u.id===g.pending.unit),after=h.units.find(u=>u.id===g.pending.unit),pos=unit&&after?(D(unit,R.center)-D(after,R.center))*w.center:0;out.push({type:'pending',opt,score:5+(value(h,s)-before)*3+pos})}out.push({type:'pending',opt:null,score:-100});return out}
 for(const u of ctx.us){if(!g.canAct(u))continue;
  if(g.canAttack(u))for(const v of g.targets(u)){let info=g.attackInfo(u,v),actual=g.previewDamage(v,info.damage).actual,lethal=v.classId==='commander'&&actual>=v.hp;out.push({type:'attack',id:u.id,target:v.id,score:lethal?100000:actual*w.attack+(actual>=v.hp?20+C[v.classId].hp:0)+(v.classId==='commander'?18:0)+(g.config.centerEnabled&&v.x===3&&v.y===3?8:0)})}
  for(const q of g.moves(u))out.push({type:'move',id:u.id,x:q.x,y:q.y,score:position(g,u,q,ctx,w)});
  if(g.canAttack(u)&&!u.sick)for(const q of g.neighbors(u).filter(q=>g.free(q.x,q.y)))for(const v of ctx.them.filter(v=>D(v,q)===1))out.push({type:'charge',id:u.id,x:q.x,y:q.y,target:v.id,score:position(g,u,q,ctx,w)+w.attack+(v.hp===1?20:0)})
 }
 if(p.ep&&g.evolutionUnlocked(s))for(const u of ctx.us.filter(u=>u.classId!=='commander'&&!u.evolved&&g.canEvolve(u))){let combat=ctx.them.some(v=>D(u,v)<=2),score=w.evolve*(combat?3:0.35)+(u.hp<=2?3:0);if(personality==='Evolution'&&p.ownTurn<6&&!combat)score-=20;out.push({type:'evolve',id:u.id,score})}
 const zones=g.summonZones(s),summonRows=g.summonRows(s),forwardRow=s==='player'?Math.min(...summonRows):Math.max(...summonRows),backRow=s==='player'?Math.max(...summonRows):Math.min(...summonRows);for(let i=0;i<p.hand.length;i++){let id=p.hand[i],card=K[id];if(!g.cardPlayable(s,i))continue;if(card.type==='unit'){if(!zones.length)continue;for(const q of zones){let fake={side:s,classId:card.classId,x:q.x,y:q.y},cost=card.cost,near=ctx.them.some(v=>D(v,q)<=1),phase1Row=card.phase1&&card.preferredRow==='back'?(q.y===backRow?10:q.y===forwardRow?-8:0):card.phase1&&card.preferredRow==='front'&&q.y===forwardRow?3:0,score=w.energy*cost+position(g,fake,q,ctx,w)*.4+(q.y===forwardRow?6:0)+phase1Row-danger(g,fake,q,ctx.them)*w.defense*.7+(near&&C[card.classId].range>1?-9:0);if(card.finisher)score+=p.ownTurn>=7?20:-12;if(card.researchStrongFinisher)score+=ctx.us.length>=3?30:-20;if(card.researchFinisher){let setup=card.finisherKind==='kingdomFinisher'?ctx.us.length>=3:card.finisherKind==='forestFinisher'?ctx.us.some(v=>D(v,ctx.cmd)<=3):card.finisherKind==='netherFinisher'?g.sides[s].graveyard.length>=3:card.finisherKind==='mechanicaFinisher';score+=setup?18:-12}if(card.entryEffect==='advance'&&g.free(q.x,q.y+(s==='player'?-1:1)))score+=w.forward*2;if(card.rush&&near)score+=w.attack*2;out.push({type:'summon',i,id,x:q.x,y:q.y,score})}}else{let opts=g.spellOptions(id,s);for(const opt of opts){let u=ctx.us.find(v=>v.id===opt.unit),v=ctx.them.find(v=>v.id===opt.target),score=w.energy*card.cost*.3;if(v){score+=w.attack*(v.hp<=1?4:2)+(v.classId==='commander'?15:0)}if(card.researchFinisher){if(card.finisherKind==='arcaneFinisher'&&v)score+=12+(D(v,ctx.cmd)<=2?12:0);if(card.finisherKind==='abyssFinisher'&&u)score+=30+(ctx.cmd.hp<=2?1000:0)}if(card.researchStrongFinisher){score+=28;if(card.finisherKind==='strongAbyss')score+=ctx.cmd.hp<=2?1000:20;if(card.finisherKind==='strongForest'&&u)score+=(D(u,ctx.cmd)-D(opt,ctx.cmd))*w.forward*4;if(card.finisherKind==='strongArcane'&&v)score+=(v.hp<=3?20:8)}if(u&&opt.x!=null)score+=position(g,u,opt,ctx,w)*.8;if(card.spellKind==='reanimate')score+=8;if(card.spellKind==='rescue'||id==='rescue')score+=8;if(card.spellKind==='fortify'&&u)score+=danger(g,u,u,ctx.them)*w.defense;if(card.spellKind==='wall')score+=2;if(['push','pull','vault','swap','breach','barrage','bloodLunge'].includes(card.spellKind)){let h=clone(g),before=ctx.us.filter(a=>g.attackInfo(a,ctx.cmd)).length;if(h.playSpell(s,i,opt)){let cmd=h.commander(enemy(s)),after=h.units.filter(a=>a.side===s&&a.state==='active'&&h.attackInfo(a,cmd)).length;score+=(after-before)*w.attack*5;if(card.spellKind==='bloodLunge')score+=ctx.own.hp<=1?-100000:-w.defense*2;if((card.spellKind==='vault'||card.spellKind==='bloodLunge')&&u)score+=(D(u,ctx.cmd)-D(opt,ctx.cmd))*w.forward*2;if(v&&v.classId!=='commander')score+=w.attack*1.5}}out.push({type:'spell',i,id,opt,score})}}
 }
 if(strength==='Basic')for(const a of out)a.score+=g.random()*50-25;
 out.sort((a,b)=>b.score-a.score);return out
}
function apply(g,s,a){if(!a)return false;switch(a.type){case'pending':return g.resolvePending(a.opt);case'attack':return g.attack(a.id,a.target);case'move':return g.move(a.id,a.x,a.y);case'charge':return g.charge(a.id,a.x,a.y,a.target);case'evolve':return g.evolve(a.id);case'summon':return !!g.summon(s,a.i,a.x,a.y);case'spell':return g.playSpell(s,a.i,a.opt)}return false}
function clone(g){let h=Object.create(Object.getPrototypeOf(g));for(const k of ['config','units','objects','sides','pending','log','damageEvents','firstUnitSummoned','reinforcementLocks','reinforcementLockEvents','reviveSuppressedEvents','commanderAdjacentSummonEvents','majorRouteSummonEvents'])h[k]=JSON.parse(JSON.stringify(g[k]));for(const k of ['nextId','winner','phase','turn','round','centerOwner','used','playerDeck','cpuDeck','firstSide','coreId','researchChargeShield','researchBreakthroughAdvanceMode','researchBreakthroughAdvance','researchFirstSummonBack','researchFirstUnitBack','researchForwardDeployment','researchReinforcementLock','researchPhase4ReviveOff','researchCommanderAdjacentSummonBlock','researchMajorRouteSummonBlock','phase4Started'])h[k]=g[k];h.random=()=>.5;return h}
function value(g,s){if(g.winner)return g.winner===s?100000:-100000;let a=context(g,s),own=a.own,opp=a.cmd,board=0;for(const u of a.us)if(u.classId!=='commander')board+=(u.hp+1)*1.3+(R.classes[u.classId].range>1?1:0);for(const u of a.them)if(u.classId!=='commander')board-=(u.hp+1)*1.3+(R.classes[u.classId].range>1?1:0);let center=g.config.centerEnabled?g.at(3,3):null;return(own.hp-opp.hp)*11+board+(center?.side===s?6:center?.side===enemy(s)?-6:0)+g.sides[s].energy*.5-g.sides[enemy(s)].energy*.5}
function tiePick(g,items,score){let best=score(items[0]),tied=items.filter(a=>Math.abs(score(a)-best)<1e-8);return tied[Math.floor(g.random()*tied.length)]||items[0]}
function explainSummon(g,s,a,personality='Balanced'){
 const w=W[personality]||W.Balanced,ctx=context(g,s),card=K[a.id],q={x:a.x,y:a.y},fake={side:s,classId:card.classId,x:q.x,y:q.y},rows=g.summonRows(s),forwardRow=s==='player'?Math.min(...rows):Math.max(...rows),nearest=Math.min(7,...ctx.them.map(v=>D(q,v))),ranged=C[card.classId].range>1,d=danger(g,fake,q,ctx.them),centerWeight=g.config.centerEnabled?w.center:0;
 const parts={energy:w.energy*card.cost,forwardRow:q.y===forwardRow?6:0,commanderDistance:0,center:0,positionDanger:-d*w.defense*(ranged?.8:.35)*.4,rangedSpacing:ranged&&nearest>=2&&nearest<=C[card.classId].range?w.ranged*.4:ranged&&nearest===1?-w.ranged*3*.4:0,exposure:-d*w.defense*.7,adjacentRangedPenalty:ranged&&ctx.them.some(v=>D(v,q)<=1)?-9:0,entryAdvance:card.entryEffect==='advance'&&g.free(q.x,q.y+(s==='player'?-1:1))?w.forward*2:0,rush:card.rush&&ctx.them.some(v=>D(v,q)<=1)?w.attack*2:0,lineOfSight:0};
 return{score:Object.values(parts).reduce((n,v)=>n+v,0),parts,cardId:a.id,classId:card.classId,ranged,x:q.x,y:q.y,forwardRow,nearestEnemy:nearest,danger:d,note:'Summon scoring has no line-of-sight term; commander/center deltas are zero because the temporary unit starts at the candidate square.'};
}
function choose(g,s,personality='Balanced',strength='Strong'){let all=candidates(g,s,personality,strength);if(!all.length)return null;if(strength==='Search'){let top=all.slice(0,Math.min(10,all.length));for(const a of top){let h=clone(g),before=value(h,s);if(apply(h,s,a)){let after=value(h,s);a.searchScore=a.score+(after-before)*3;if(!h.pending&&!h.winner){h.turn=enemy(s);h.used=0;for(const u of h.units.filter(v=>v.side===h.turn)){u.acted=false;u.sick=false}let threats=candidates(h,enemy(s),personality,'Strong').filter(v=>v.type==='attack').slice(0,4);if(threats.length)a.searchScore-=Math.max(...threats.map(v=>v.score))*0.25}}else a.searchScore=-Infinity}top.sort((a,b)=>b.searchScore-a.searchScore);return tiePick(g,top,a=>a.searchScore)}return tiePick(g,all,a=>a.score)}
window.CoreAI={personalities:Object.keys(W),strengths:['Basic','Strong','Search'],weights:W,candidates,choose,apply,explainSummon};
})();
