/* Ver.0.38 Human Playtest logger. Data collection only; never changes rules or AI. */
(function(){'use strict';
const R=window.RULES,K=R.cards,C=R.classes,KEY='tactics7_human_playtest_v038',clone=v=>JSON.parse(JSON.stringify(v)),iso=()=>new Date().toISOString();
let active=null,pending=null,lastSig='',enabled=new URLSearchParams(location.search).get('playtest')==='1';
function rng(seed){let x=seed>>>0;return()=>((x^=x<<13,x^=x>>>17,x^=x<<5)>>>0)/4294967296}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{schema:'tactics7-human-playtest-0.38',matches:[]}}catch{return{schema:'tactics7-human-playtest-0.38',matches:[]}}}function save(db){localStorage.setItem(KEY,JSON.stringify(db))}
function ply(g){return Math.max(1,g.sides.player.ownTurn+g.sides.cpu.ownTurn)}function time(g){let p=ply(g);return{ply:p,round:Math.ceil(p/2),playerTurn:g.sides[g.turn]?.ownTurn||Math.ceil(p/2),actingSide:g.turn}}
function cleanAction(a){if(!a)return null;let o={type:a.type};for(const k of ['id','target','x','y','i'])if(a[k]!=null)o[k]=a[k];if(a.id&&K[a.id]){o.cardId=a.id;o.cardName=K[a.id].name}if(a.opt)o.option=clone(a.opt);return o}
function legal(g){if(g.turn!=='player'||g.winner)return[];try{return [...CoreAI.candidates(g,'player','Balanced','Strong').map(cleanAction),{type:'endTurn'}]}catch{return[]}}
function state(g){return{...time(g),turn:g.turn,roundEngine:g.round,usedActions:g.used,board:g.units.filter(u=>u.state!=='grave').map(u=>({id:u.id,cardId:u.cardId,classId:u.classId,side:u.side,x:u.x,y:u.y,hp:u.hp,maxHp:u.maxHp,state:u.state,evolved:u.evolved,acted:u.acted,sick:u.sick,guard:u.guard||0})),objects:clone(g.objects||[]),hand:g.sides.player.hand.slice(),energy:{player:g.sides.player.energy,cpu:g.sides.cpu.energy},energyCap:{player:g.sides.player.turnEnergyCap,cpu:g.sides.cpu.turnEnergyCap},ep:{player:g.sides.player.ep,cpu:g.sides.cpu.ep},commanderHp:{player:g.commander('player').hp,cpu:g.commander('cpu').hp},graveyard:{player:g.sides.player.graveyard.slice(),cpu:g.sides.cpu.graveyard.slice()},deckCount:{player:g.sides.player.deck.length,cpu:g.sides.cpu.deck.length}}}
function signature(g){let s=state(g);return JSON.stringify([s.ply,s.turn,s.usedActions,s.hand,s.energy,s.ep,s.board.map(u=>[u.id,u.x,u.y,u.hp,u.state,u.evolved,u.acted])])}
function start(g,m={}){if(!enabled)return;let seed=m.seed??Math.floor(Math.random()*0xffffffff),pd=R.decks[g.playerDeck],cd=R.decks[g.cpuDeck];active={matchId:`PT-${Date.now().toString(36)}-${seed.toString(36)}`,testerId:(m.testerId||localStorage.getItem('tactics7_tester_id')||'Tester-001').trim(),timestamp:iso(),source:'human_playtest',gameVersion:'0.41',cardSetVersion:'0.37-phase1',logSchemaVersion:'0.41',coreVersion:'F1-H2-G2R-research',syncStatus:window.PlaytestCloud?.hasConsent()?'pending':'local_only',core:{coreId:g.coreId,F1:g.researchForwardDeployment,H2:g.researchFirstUnitBack,G2R:g.researchBreakthroughAdvanceMode},seed,human:{classId:pd.classId,deckId:g.playerDeck},cpu:{classId:cd.classId,deckId:g.cpuDeck},firstSide:g.firstSide,result:null,decisions:[],uiEvents:[],survey:null,replay:{initialHands:null,actions:[]}};pending=null;lastSig='';localStorage.setItem('tactics7_tester_id',active.testerId)}
function decision(g){if(!active||g.turn!=='player'||g.winner)return;let s=signature(g);if(s===lastSig&&pending)return;lastSig=s;pending={decisionId:`${active.matchId}-D${active.decisions.length+1}`,startedAt:performance.now(),wallTime:iso(),state:state(g),legalActions:legal(g)}}
function infer(before,after,meta={}){let moved=after.board.find(u=>{let b=before.board.find(v=>v.id===u.id);return b&&(b.x!==u.x||b.y!==u.y)}),damaged=after.board.find(u=>{let b=before.board.find(v=>v.id===u.id);return b&&u.hp<b.hp}),newUnit=after.board.find(u=>!before.board.some(v=>v.id===u.id)),ep=before.ep.player-after.ep.player,energy=before.energy.player-after.energy.player;if(before.turn!==after.turn)return{type:'endTurn'};if(newUnit)return{type:'summon',cardId:newUnit.cardId,unitId:newUnit.id,x:newUnit.x,y:newUnit.y};if(ep>0)return{type:'evolve',unitId:meta.points?.from?.id||moved?.id||damaged?.id||null};if(energy>0){let cardId=before.hand.find(id=>!after.hand.includes(id))||null;return{type:K[cardId]?.type==='spell'?'spell':'cardUse',cardId:before.hand.find(id=>!after.hand.includes(id))||null,targetId:damaged?.id||null,x:moved?.x,y:moved?.y}}if(damaged)return{type:meta.message?.includes('突撃')?'charge':'attack',targetId:damaged.id,unitId:meta.points?.from?.id||moved?.id||null};if(moved)return{type:'move',unitId:moved.id,x:moved.x,y:moved.y};return{type:'effectResolution',label:meta.message||null}}
function outcome(before,after){let b=new Map(before.board.map(u=>[u.id,u])),ev=[];for(const u of after.board){let v=b.get(u.id);if(!v)ev.push({type:u.classId==='lab_token'?'token':'unitCreated',unitId:u.id,cardId:u.cardId,x:u.x,y:u.y});else{if(v.x!==u.x||v.y!==u.y)ev.push({type:'move',unitId:u.id,from:{x:v.x,y:v.y},to:{x:u.x,y:u.y}});if(v.hp!==u.hp)ev.push({type:u.hp<v.hp?'damage':'heal',unitId:u.id,amount:Math.abs(v.hp-u.hp),commander:u.classId==='commander'});if(v.state!==u.state)ev.push({type:u.state==='down'?'down':'state',unitId:u.id,from:v.state,to:u.state});if(!v.evolved&&u.evolved)ev.push({type:'evolve',unitId:u.id})}}if(before.energy.player!==after.energy.player)ev.push({type:'energy',from:before.energy.player,to:after.energy.player});if(before.ep.player!==after.ep.player)ev.push({type:'ep',from:before.ep.player,to:after.ep.player});return ev}
function commit(g,meta={}){if(!active)return;let before=pending?.state||state(g),after=state(g),chosen=infer(before,after,meta);if(meta.inputMethod)chosen.inputMethod=meta.inputMethod;let entry={...(pending||{decisionId:`${active.matchId}-D${active.decisions.length+1}`,startedAt:performance.now(),wallTime:iso(),state:before,legalActions:legal(g)}),chosenAction:chosen,decisionTimeMs:Math.round(performance.now()-(pending?.startedAt||performance.now())),outcome:outcome(before,after)};if(['attack','charge'].includes(chosen.type)&&entry.outcome.some(e=>e.type==='down')&&entry.outcome.some(e=>e.type==='move'))entry.outcome.push({type:'g2r'});active.decisions.push(entry);active.replay.actions.push({time:time(g),action:chosen,outcome:entry.outcome});pending=null;lastSig='';persist()}
function ui(type,data={}){if(active)active.uiEvents.push({type,...(pending?.state?{ply:pending.state.ply,round:pending.state.round,playerTurn:pending.state.playerTurn}:{}),timestamp:iso(),...clone(data)})}
function initialHands(g,mulligan){if(active)active.replay.initialHands={player:g.sides.player.hand.slice(),cpu:g.sides.cpu.hand.slice(),mulligan:mulligan.slice()}}
function persist(){if(!active)return;let db=load(),i=db.matches.findIndex(m=>m.matchId===active.matchId);if(i>=0)db.matches[i]=clone(active);else db.matches.push(clone(active));save(db)}
function finish(g,reason='commanderDown'){if(!active||active.result)return;let t=time(g);active.result={winner:g.winner||'abandoned',humanResult:g.winner==='player'?'win':g.winner==='cpu'?'loss':'draw',endPly:t.ply,endRound:t.round,endPlayerTurn:g.sides.player.ownTurn,commanderHp:{player:g.commander('player').hp,cpu:g.commander('cpu').hp},reason,endedAt:iso()};persist();window.PlaytestCloud?.queue(active)}
function survey(v){if(!active)return;active.survey={fun:v.fun?+v.fun:null,clarity:v.clarity?+v.clarity:null,balanceCard:v.balanceCard||'',playAgain:v.playAgain||null,comment:v.comment||'',submittedAt:iso()};persist();window.PlaytestCloud?.queue(active)}
function exportJSON(){let db=load(),blob=new Blob([JSON.stringify({...db,exportedAt:iso()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tactics7_playtest_${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importJSON(file){let data=JSON.parse(await file.text()),items=Array.isArray(data)?data:data.matches;if(!Array.isArray(items))throw Error('matches配列がありません');let db=load(),map=new Map(db.matches.map(m=>[m.matchId,m]));for(const m of items)if(m?.matchId)map.set(m.matchId,m);db.matches=[...map.values()];save(db);return analyze(db.matches)}
function analyze(matches=load().matches){let done=matches.filter(m=>m.result),by=key=>{let o={};for(const m of done){let k=key(m)||'unknown',x=o[k]||(o[k]={games:0,wins:0});x.games++;x.wins+=m.result.humanResult==='win'}for(const x of Object.values(o))x.winRate=x.games?x.wins/x.games:null;return o},actions={},cards={},details={},finishTurns=[],evolves={},summon={front:0,back:0,rangedFront:0,rangedBack:0},times=[],surveys=[];for(const m of done){for(const d of m.decisions||[]){let a=d.chosenAction;if(a?.type)actions[a.type]=(actions[a.type]||0)+1;if(a?.cardId){cards[a.cardId]=(cards[a.cardId]||0)+1;if(K[a.cardId]?.finisher)finishTurns.push(d.state.playerTurn)}if(Number.isFinite(d.decisionTimeMs))times.push(d.decisionTimeMs);if(a?.type==='evolve'){let u=d.state.board.find(v=>v.id===a.unitId),id=u?.cardId||u?.classId||'unknown';evolves[id]=(evolves[id]||0)+1}if(a?.type==='summon'){let c=K[a.cardId],front=a.y===4,ranged=c?.type==='unit'&&C[c.classId]?.range>=2;summon[front?'front':'back']++;if(ranged)summon[front?'rangedFront':'rangedBack']++}}for(const e of m.uiEvents||[])if(e.type==='cardDetailOpen')details[e.cardId]=(details[e.cardId]||0)+1;if(m.survey)surveys.push(m.survey)}times.sort((a,b)=>a-b);let dist={};for(const m of done)dist[m.result.endPlayerTurn]=(dist[m.result.endPlayerTurn]||0)+1;let fun=surveys.filter(v=>v.fun),clarity=surveys.filter(v=>v.clarity);return{schema:'tactics7-human-summary-0.38',matches:done.length,humanWins:done.filter(m=>m.result.humanResult==='win').length,humanWinRate:done.length?done.filter(m=>m.result.humanResult==='win').length/done.length:null,byClass:by(m=>m.human.classId),byDeck:by(m=>m.human.deckId),byFirstSecond:by(m=>m.firstSide==='player'?'first':'second'),playerTurnDistribution:dist,actions,cardUsage:cards,cardDetailViews:details,finisherUsePlayerTurns:finishTurns,evolutionTargets:evolves,summonPositions:summon,decisionTime:{count:times.length,medianMs:times.length?times[times.length>>1]:null,p90Ms:times.length?times[Math.floor(times.length*.9)]:null,over60s:times.filter(v=>v>60000).length},survey:{count:surveys.length,meanFun:fun.length?fun.reduce((n,v)=>n+v.fun,0)/fun.length:null,meanClarity:clarity.length?clarity.reduce((n,v)=>n+v.clarity,0)/clarity.length:null,playAgainYes:surveys.filter(v=>v.playAgain==='yes').length,comments:surveys.filter(v=>v.comment||v.balanceCard)}}}
function clear(){localStorage.removeItem(KEY)}
window.addEventListener('tactics7-sync-status',e=>{let {matchId,status}=e.detail||{},db=load(),m=db.matches.find(v=>v.matchId===matchId);if(m){m.syncStatus=status;save(db)}if(active?.matchId===matchId)active.syncStatus=status});
window.HumanPlaytest={get enabled(){return enabled},setEnabled:v=>enabled=!!v,get active(){return active},rng,start,decision,commit,ui,initialHands,finish,survey,exportJSON,importJSON,analyze,load,clear,state,legal};
})();
