/* CORE LAB: deterministic, editable prototype pool. Every generated card has a
   named battlefield role, a playable effect, and a class/archetype identity. */
(function(){'use strict';
const R=window.RULES;
const groups=[
 {id:'Kingdom',jp:'王国',icon:'♜',archetypes:['Aggro','Tempo','Formation'],unitEffects:['advance','guardAdjacent','drawIfCenter','guardAdjacent','advance','drawIfCenter'],spells:['advance','fortify','swap'],shapes:[null,null,null,null,{directions:'orthogonal',unitPierce:0,terrainPierce:0},null]},
 {id:'Forest',jp:'森域',icon:'✿',archetypes:['Swarm','Mobility','Combo'],unitEffects:['advance','advance','drawIfCenter','swapAdjacent','advance','swapAdjacent'],spells:['advance','swap','retreat'],shapes:[null,null,null,{directions:'diagonal',unitPierce:0,terrainPierce:0},null,null]},
 {id:'Arcane',jp:'魔導',icon:'✧',archetypes:['SpellTempo','Control','Position'],unitEffects:['draw','pushEnemy','pullEnemy','draw','pushEnemy','pullEnemy'],spells:['push','pull','snipe'],shapes:[null,null,{directions:'queen',unitPierce:1,terrainPierce:0},null,{directions:'orthogonal',unitPierce:0,terrainPierce:0},null]},
 {id:'Nether',jp:'冥界',icon:'☾',archetypes:['Sacrifice','Reanimate','Control'],unitEffects:['draw','reanimate','drawIfGrave','reanimate','drawIfGrave','reanimate'],spells:['rescue','drain','reanimate'],shapes:[null,null,null,null,{directions:'queen',unitPierce:0,terrainPierce:0},null]},
 {id:'Mechanica',jp:'機巧',icon:'⚙',archetypes:['Fortification','Token','Artillery'],unitEffects:['wall','token','guardAdjacent','wall','token','wall'],spells:['wall','token','fortify'],shapes:[null,null,null,null,{directions:'orthogonal',unitPierce:0,terrainPierce:0},null]},
 {id:'Abyss',jp:'深淵',icon:'◆',archetypes:['Aggro','SelfDamage','Combo'],unitEffects:['selfHarmAdvance','selfHarmDraw','advance','selfHarmAdvance','drain','selfHarmDraw'],spells:['selfHarmRush','drain','snipe'],shapes:[null,null,null,null,{directions:'queen',unitPierce:0,terrainPierce:0},null]}
];
const costs=[1,2,3,4,5,7],hp=[2,3,4,4,5,6],melee=[1,1,2,2,2,3];
const descriptions={advance:'登場時に前方1マス進む',guardAdjacent:'隣接味方へ防御+1',drawIfCenter:'中央支配時に1ドロー',swapAdjacent:'登場時に隣接味方と交換',draw:'登場時に1ドロー',pushEnemy:'隣接敵を1マス押す',pullEnemy:'2マス先の敵を引き寄せる',reanimate:'墓地の低コストユニットを復帰',drawIfGrave:'墓地にカードがあれば1ドロー',wall:'空き隣接マスへ一時壁を設置',token:'隣接マスへ小型トークンを召喚',selfHarmAdvance:'リーダーHPを1失い前方1マス進む',selfHarmDraw:'リーダーHPを1失い1ドロー',drain:'敵に1ダメージ、リーダーを1回復',fortify:'味方1体へ防御+1',swap:'隣接味方2体を交換',retreat:'味方を自陣方向へ1マス移動',push:'敵を1マス押し出す',pull:'敵を1マス引き寄せる',snipe:'敵に遠隔1ダメージ',rescue:'DOWNした味方をHP1で復帰',selfHarmRush:'リーダーHPを1失い味方を1マス前進'};
R.research={classes:groups.map(g=>g.id),neutral:'Neutral',archetypes:{},cards:[],decks:[],effects:descriptions};
for(const g of groups){R.research.archetypes[g.id]=g.archetypes.slice();for(let tier=0;tier<6;tier++){let cls=`lab_${g.id}_${tier}`,shape=g.shapes[tier],ranged=shape?(tier>=4?2:1):0,range=shape?(tier>=4?3:2):0;R.classes[cls]={name:`${g.jp} ${['斥候','先兵','中衛','遊撃','射手','切札'][tier]}`,icon:g.icon,hp:hp[tier]+(g.id==='Mechanica'&&tier>2?1:0)-(g.id==='Abyss'?1:0),melee:melee[tier]+(g.id==='Abyss'&&tier>2?1:0),range,ranged,rangedDamageType:g.id==='Arcane'?'magic':'ranged_projectile',line:shape?.unitPierce?'oneUnit':shape?.directions==='orthogonal'?'straight':'clear',attackShape:shape?{...shape,engaged:false}:null,moveTrait:g.id==='Forest'&&tier%2===0?{type:'orthogonal',steps:2}:null,evolution:['step','swap','push','stepStrike','shiftEnemy','stepStrike'][tier],description:`${g.jp}の実験用${['軽量','前衛','連携','機動','射線','決着'][tier]}ユニット。`}}
  for(let ai=0;ai<3;ai++){let arc=g.archetypes[ai],cards=[];for(let j=0;j<9;j++){let id=`TEST_${g.id}_${String(ai*9+j+1).padStart(2,'0')}`,unit=j<6,effect=unit?g.unitEffects[(j+ai*2)%6]:g.spells[(j-6+ai)%3],cost=unit?costs[j]:[1,3,6][j-6],card={name:id,type:unit?'unit':'spell',classId:unit?`lab_${g.id}_${j}`:undefined,cost,tags:[g.id,arc],className:g.jp,archetype:arc,effect:descriptions[effect],entryEffect:unit?effect:null,spellKind:unit?null:effect,art:{normal:null,evolved:null}};if(g.id==='Nether'&&unit&&j%3===0)card.onDown='draw';R.cards[id]=card;R.research.cards.push(id);cards.push(id)}let neutral=`TEST_Neutral_${String((ai+groups.indexOf(g)*3)%15+1).padStart(2,'0')}`,deckId=`lab_${g.id}_${arc}`;R.decks[deckId]={name:`${g.jp} / ${arc}`,description:`${g.jp}の${arc}を検証する20枚デッキ`,classId:g.id,archetype:arc,cards:[...cards.flatMap(id=>[id,id]),neutral,neutral]};R.research.decks.push(deckId)}}
for(let i=0;i<15;i++){let id=`TEST_Neutral_${String(i+1).padStart(2,'0')}`,unit=i<9,effect=['advance','guardAdjacent','draw','retreat','fortify','swap','rescue','snipe','wall','token','drawIfCenter','push','pull','drain','reanimate'][i],tier=i%6;if(unit){let cls=`lab_Neutral_${i}`;R.classes[cls]={name:`Neutral ${i+1}`,icon:'◇',hp:hp[tier],melee:melee[tier],range:0,ranged:0,line:'none',attackShape:null,moveTrait:null,evolution:'step',description:'汎用の実験用ユニット。'}}R.cards[id]={name:id,type:unit?'unit':'spell',classId:unit?`lab_Neutral_${i}`:undefined,cost:unit?costs[tier]:[1,2,2,3,4,5][i-9],tags:['Neutral'],className:'Neutral',archetype:'Utility',effect:descriptions[effect],entryEffect:unit?effect:null,spellKind:unit?null:effect,art:{normal:null,evolved:null}};R.research.cards.push(id)}
R.validateDeck=function(cards,classId){if(cards.length!==20)return{ok:false,reason:'20枚ではありません'};let counts={};for(const id of cards){let c=R.cards[id];if(!c)return{ok:false,reason:`不明なカード ${id}`};if(++counts[id]>R.deckCopyLimit)return{ok:false,reason:`同名上限超過 ${id}`};if(classId&&c.className!==classId&&c.className!=='Neutral'&&c.tags?.[0]!==classId)return{ok:false,reason:`クラス違い ${id}`};if(c.className==='Neutral'&&!R.allowNeutral)return{ok:false,reason:'Neutral使用不可'}}return{ok:true}}
})();
window.RULES.classes.lab_token={name:'仮トークン',icon:'◇',hp:2,melee:1,range:0,ranged:0,line:'none',moveTrait:null,evolution:'step',description:'研究用の生成ユニット。'};
