/* Shared research-only deck generator for Set 1 Prototype balance studies. */
(function(){'use strict';const R=RULES,K=R.cards;
const profiles={Tempo:['early','advance','mobility','breakthrough'],Midrange:['frontline','advance','evolution','breakthrough','ranged'],Control:['defense','recovery','removal','position','ranged','value'],Mechanic:['token','position','evolution','value','advance'],Power:['early','frontline','advance','breakthrough','evolution']};
const aliases={Kingdom:{Mechanic:['advance','evolution','defense']},Forest:{Mechanic:['mobility','position','breakthrough']},Arcane:{Mechanic:['ranged','position','breakthrough']},Nether:{Mechanic:['value','recovery','advance']},Mechanica:{Mechanic:['token','ranged','position']},Abyss:{Mechanic:['advance','value','recovery']}};
function hash(s){let x=2166136261;for(const c of s)x=(x^c.charCodeAt(0))*16777619>>>0;return x}
function score(id,cl,name){let c=K[id],roles=aliases[cl]?.[name]||profiles[name],s=(roles.includes(c.role)?40:0)+(c.cost<=3&&name==='Tempo'?14:0)+(c.finisher&&name==='Control'?5:0)+(c.finisher&&name==='Power'?9:0)+(c.set1Change?.kind==='TUNE'?2:0);if(name==='Power')s+=(c.cost<=6?6:0)+(c.type==='unit'?2:0);return s+hash(name+id)%7}
function cards(cl,name){let pool=R.set1Prototype.byClass[cl].slice().sort((a,b)=>score(b,cl,name)-score(a,cl,name)),chosen=[],costs={};for(const id of pool){let band=K[id].cost<=3?0:K[id].cost<=6?1:2,limits=name==='Tempo'?[6,3,1]:name==='Control'?[3,5,2]:[4,4,2];if((costs[band]||0)>=limits[band])continue;chosen.push(id);costs[band]=(costs[band]||0)+1;if(chosen.length===10)break}for(const id of pool)if(chosen.length<10&&!chosen.includes(id))chosen.push(id);return chosen.slice(0,10).flatMap(id=>[id,id])}
function install(prefix='s1'){let ids=[],meta={};for(const cl of Object.keys(R.set1Prototype.byClass))for(const name of Object.keys(profiles)){let id=`${prefix}_${cl}_${name}`,deck=cards(cl,name);R.decks[id]={name:`${R.phase1.identities[cl].name} / ${name}`,description:'Set 1 research deck',classId:cl,cards:deck};ids.push(id);meta[id]={classId:cl,archetype:name,cards:deck}}return{ids,meta}}
window.Set1Decks={profiles,score,cards,install};})();
