/* TACTICS 7 Ver.0.51 Preview UI shell. Rules, cards and AI remain unchanged. */
(function(){'use strict';
const $=s=>document.querySelector(s),R=window.RULES,K=R.cards;
const UI={screen:'boot',history:[],set(screen){if(this.screen!==screen){this.history.push(this.screen);this.screen=screen;document.body.dataset.uiScreen=screen;window.HumanPlaytest?.ui?.('uiScreen',{screen})}},back(){return this.history.pop()||'lobby'}};
function cardModel(id,context={}){let c=K[id],cl=c?.classId&&R.classes[c.classId];return{id,name:c?.name||id,cost:c?.cost??0,type:c?.type||'',classId:c?.classId||'',role:c?.role||'',attack:cl?.melee??null,hp:cl?.hp??null,range:cl?.range??null,effect:c?.effect||'',keywords:c?.keywords||[],count:context.count??null,selected:!!context.selected,disabled:!!context.disabled}}
function card(model,size='list'){let stats=model.type==='unit'?`ATK ${model.attack} / HP ${model.hp}${model.range?` / 射程 ${model.range}`:''}`:'スペル';return `<article class="t7-card t7-card--${size}${model.selected?' is-selected':''}${model.disabled?' is-disabled':''}" data-card="${model.id}"><i>${model.cost}</i><b>${model.name}</b><small>${stats}</small>${model.count!=null?`<em>${model.count}/2</em>`:''}</article>`}
window.T7UI={state:UI,components:{cardModel,card},tokens:true};
function screenOf(root){if(root.querySelector('.idGate'))return'id';if(root.querySelector('.consentScreen'))return'consent';if(root.querySelector('.lobby50'))return'lobby';if(root.querySelector('.decks49'))return'decks';if(root.querySelector('.classGrid49'))return'class-select';if(root.querySelector('.builder50'))return'deck-builder';if(root.querySelector('.catalog50'))return'cards';if(root.querySelector('.battle49'))return'match';if(root.querySelector('.how50,.rules50'))return'howto';if(root.querySelector('.settings50'))return'settings';if(root.querySelector('.mulliganCard'))return'mulligan';if(root.querySelector('.result51')||/勝利|敗北/.test(root.textContent))return'result';return'battle'}
function enhanceLobby(root){let lobby=root.querySelector('.lobby50');if(!lobby||lobby.dataset.v51)return;lobby.dataset.v51='1';lobby.insertAdjacentHTML('afterbegin','<div class="t7-hero-slot" aria-hidden="true"></div>');let small=lobby.querySelector(':scope>small');if(small)small.textContent='';for(const [go,label] of [['battle','対戦する'],['decks','デッキ'],['cards','カードコレクション']]){let b=lobby.querySelector(`[data-go="${go}"]`);if(b)b.textContent=label}}
function enhanceCollection(root){let page=root.querySelector('.catalog50');if(!page||page.dataset.v51)return;page.dataset.v51='1';let tools=page.querySelector('.catalogTools'),grid=page.querySelector('#v50catalog');if(!tools||!grid)return;tools.insertAdjacentHTML('afterend','<div class="t7-collection-filters"><input id="v51cardSearch" type="search" placeholder="カード名・能力・キーワードを検索" aria-label="カード検索"><select id="v51cost"><option value="">全COST</option><option value="1-3">1〜3</option><option value="4-6">4〜6</option><option value="7-10">7〜10</option></select><select id="v51type"><option value="">全種類</option><option value="unit">ユニット</option><option value="spell">スペル</option></select><input id="v51keyword" placeholder="キーワード" aria-label="キーワード絞り込み"></div>');let apply=()=>{let q=$('#v51cardSearch')?.value.trim().toLowerCase()||'',cost=$('#v51cost')?.value||'',type=$('#v51type')?.value||'',kw=$('#v51keyword')?.value.trim().toLowerCase()||'',shown=0;for(const row of grid.querySelectorAll('.buildCard')){let id=row.dataset.card,c=K[id],text=`${c.name} ${c.effect||''} ${(c.keywords||[]).join(' ')}`.toLowerCase(),costOK=!cost||(cost==='1-3'?c.cost<=3:cost==='4-6'?c.cost>=4&&c.cost<=6:c.cost>=7),ok=(!q||text.includes(q))&&(!type||c.type===type)&&(!kw||text.includes(kw))&&costOK;row.hidden=!ok;shown+=ok}let empty=grid.querySelector('.t7-empty');if(!shown&&!empty)grid.insertAdjacentHTML('beforeend','<p class="t7-empty">条件に合うカードがありません</p>');else if(shown&&empty)empty.remove()};for(const id of ['v51cardSearch','v51cost','v51type','v51keyword'])$('#'+id)?.addEventListener('input',apply);new MutationObserver(apply).observe(grid,{childList:true})}
function enhanceMulligan(root){let cards=root.querySelectorAll('.mulliganCard');if(!cards.length||root.dataset.v51Mulligan)return;root.dataset.v51Mulligan='1';root.querySelector('h2').textContent='最初の手札を選ぶ';let p=root.querySelector('h2+p');if(p)p.textContent='残すカードはKEEP、交換するカードを選ぶとCHANGEになります。';cards.forEach(c=>{c.setAttribute('role','button');c.setAttribute('aria-pressed','false');c.addEventListener('click',()=>c.setAttribute('aria-pressed',String(c.classList.contains('on'))))});let done=root.querySelector('#mulliganDone');if(done)done.textContent='この手札で対戦開始'}
function resultData(){let g=window.TacticsUI?.game,d=R.decks[g?.playerDeck];return{g,d,won:g?.winner==='player',pt:g?.sides?.player?.ownTurn||0,round:g?.round||0}}
function enhanceResult(root){if(root.querySelector('.result51')||!root.querySelector('#resultRestart')||!/勝利|敗北/.test(root.textContent))return;let {g,d,won,pt,round}=resultData(),form=root.querySelector('#ptSurvey'),sync=root.querySelector('#syncNotice'),wrap=document.createElement('div');wrap.className=`result51 ${won?'win':'lose'}`;wrap.innerHTML=`<div class="resultWord">${won?'WIN':'LOSE'}</div><h2>${won?'勝利しました':'あと一歩でした'}</h2><div class="resultStats"><span class="t7-badge">${d?.name||'使用デッキ'}</span><span class="t7-badge">Player Turn ${pt}</span><span class="t7-badge">Round ${round}</span></div><div class="resultActions"><button id="v51rematch" class="primaryHome">もう一戦</button><button id="v51lobby">ロビー</button>${d?.isCustom?'<button id="v51edit">デッキを編集</button>':''}</div>`;if(sync){let box=document.createElement('div');box.className='t7-sync';box.append(sync);wrap.append(box)}if(form){let survey=document.createElement('section');survey.className='resultSurvey';survey.innerHTML='<b>任意アンケート</b><p>次の改善に使う短い質問です。</p>';survey.append(form);wrap.append(survey)}root.innerHTML='';root.append(wrap);$('#v51rematch').onclick=()=>window.TacticsUI.start(g.playerDeck,g.cpuDeck);$('#v51lobby').onclick=()=>window.DeckBuilderV50.lobby();if($('#v51edit'))$('#v51edit').onclick=()=>{let row=window.DeckStoreV49.read().find(x=>x.deckId===g.playerDeck);row?window.DeckBuilderV50.open(row):window.DeckBuilderV50.decks()};if(form)form.onsubmit=e=>{e.preventDefault();window.HumanPlaytest.survey(Object.fromEntries(new FormData(form)));window.DeckBuilderV50.lobby()}}
function enhanceSync(){let n=$('#syncNotice');if(!n)return;let text=n.textContent;n.dataset.status=/失敗/.test(text)?'failed':/保存|再送/.test(text)?'pending':'synced'}
function enhance(){let root=$('#dialog');if(!root)return;UI.set(screenOf(root));enhanceLobby(root);enhanceCollection(root);enhanceMulligan(root);enhanceResult(root);enhanceSync();root.querySelectorAll('.buildCard').forEach(x=>x.setAttribute('role','listitem'));root.querySelectorAll('.buildCards').forEach(x=>x.setAttribute('role','list'))}
let scheduled=false,obs=new MutationObserver(()=>{if(scheduled)return;scheduled=true;setTimeout(()=>{scheduled=false;enhance()},0)});obs.observe(document.documentElement,{subtree:true,childList:true});enhance();
})();
